//*****************************************************************************
// Copyright (c) 2021 - Allen Cummings, RealmsMUD, All rights reserved. See
//                      the accompanying LICENSE file for details.
//*****************************************************************************
inherit "/lib/environment/region.c";

/////////////////////////////////////////////////////////////////////////////
public void Setup()
{
    setRegionName("Tol-Dhurath Forest 2");
    setRegionType("forest");
    setDimensions(25, 10);
    // EntryCoordinate

    setCoordinate(0, 0,
        "/areas/tol-dhurath/forest-2/0x0.c", "room");
    setCoordinate(0, 2,
        "/areas/tol-dhurath/forest-2/0x2.c", "room");
    setCoordinate(0, 4,
        "/areas/tol-dhurath/forest-2/0x4.c", "entry");
    setCoordinate(10, 1,
        "/areas/tol-dhurath/forest-2/10x1.c", "path");
    setCoordinate(10, 3,
        "/areas/tol-dhurath/forest-2/10x3.c", "path");
    setCoordinate(10, 4,
        "/areas/tol-dhurath/forest-2/10x4.c", "path");
    setCoordinate(10, 6,
        "/areas/tol-dhurath/forest-2/10x6.c", "room");
    setCoordinate(10, 8,
        "/areas/tol-dhurath/forest-2/10x8.c", "path");
    setCoordinate(10, 9,
        "/areas/tol-dhurath/forest-2/10x9.c", "room");
    setCoordinate(11, 0,
        "/areas/tol-dhurath/forest-2/11x0.c", "room");
    setCoordinate(11, 1,
        "/areas/tol-dhurath/forest-2/11x1.c", "path");
    setCoordinate(11, 3,
        "/areas/tol-dhurath/forest-2/11x3.c", "path");
    setCoordinate(11, 4,
        "/areas/tol-dhurath/forest-2/11x4.c", "path");
    setCoordinate(11, 5,
        "/areas/tol-dhurath/forest-2/11x5.c", "path");
    setCoordinate(11, 6,
        "/areas/tol-dhurath/forest-2/11x6.c", "path");
    setCoordinate(11, 7,
        "/areas/tol-dhurath/forest-2/11x7.c", "path");
    setCoordinate(11, 8,
        "/areas/tol-dhurath/forest-2/11x8.c", "path");
    setCoordinate(11, 9,
        "/areas/tol-dhurath/forest-2/11x9.c", "path");
    setCoordinate(12, 0,
        "/areas/tol-dhurath/forest-2/12x0.c", "room");
    setCoordinate(12, 3,
        "/areas/tol-dhurath/forest-2/12x3.c", "room");
    setCoordinate(12, 4,
        "/areas/tol-dhurath/forest-2/12x4.c", "path");
    setCoordinate(12, 6,
        "/areas/tol-dhurath/forest-2/12x6.c", "path");
    setCoordinate(12, 7,
        "/areas/tol-dhurath/forest-2/12x7.c", "path");
    setCoordinate(12, 8,
        "/areas/tol-dhurath/forest-2/12x8.c", "path");
    setCoordinate(12, 9,
        "/areas/tol-dhurath/forest-2/12x9.c", "path");
    setCoordinate(13, 0,
        "/areas/tol-dhurath/forest-2/13x0.c", "path");
    setCoordinate(13, 6,
        "/areas/tol-dhurath/forest-2/13x6.c", "path");
    setCoordinate(13, 7,
        "/areas/tol-dhurath/forest-2/13x7.c", "path");
    setCoordinate(13, 8,
        "/areas/tol-dhurath/forest-2/13x8.c", "path");
    setCoordinate(14, 0,
        "/areas/tol-dhurath/forest-2/14x0.c", "path");
    setCoordinate(14, 1,
        "/areas/tol-dhurath/forest-2/14x1.c", "path");
    setCoordinate(14, 2,
        "/areas/tol-dhurath/forest-2/14x2.c", "path");
    setCoordinate(14, 6,
        "/areas/tol-dhurath/forest-2/14x6.c", "room");
    setCoordinate(14, 8,
        "/areas/tol-dhurath/forest-2/14x8.c", "path");
    setCoordinate(14, 9,
        "/areas/tol-dhurath/forest-2/14x9.c", "path");
    setCoordinate(15, 1,
        "/areas/tol-dhurath/forest-2/15x1.c", "path");
    setCoordinate(15, 2,
        "/areas/tol-dhurath/forest-2/15x2.c", "path");
    setCoordinate(15, 3,
        "/areas/tol-dhurath/forest-2/15x3.c", "path");
    setCoordinate(15, 4,
        "/areas/tol-dhurath/forest-2/15x4.c", "path");
    setCoordinate(15, 6,
        "/areas/tol-dhurath/forest-2/15x6.c", "room");
    setCoordinate(15, 7,
        "/areas/tol-dhurath/forest-2/15x7.c", "room");
    setCoordinate(15, 8,
        "/areas/tol-dhurath/forest-2/15x8.c", "path");
    setCoordinate(15, 9,
        "/areas/tol-dhurath/forest-2/15x9.c", "path");
    setCoordinate(16, 0,
        "/areas/tol-dhurath/forest-2/16x0.c", "path");
    setCoordinate(16, 1,
        "/areas/tol-dhurath/forest-2/16x1.c", "path");
    setCoordinate(16, 2,
        "/areas/tol-dhurath/forest-2/16x2.c", "room");
    setCoordinate(16, 3,
        "/areas/tol-dhurath/forest-2/16x3.c", "path");
    setCoordinate(16, 4,
        "/areas/tol-dhurath/forest-2/16x4.c", "path");
    setCoordinate(16, 5,
        "/areas/tol-dhurath/forest-2/16x5.c", "path");
    setCoordinate(16, 7,
        "/areas/tol-dhurath/forest-2/16x7.c", "path");
    setCoordinate(16, 8,
        "/areas/tol-dhurath/forest-2/16x8.c", "path");
    setCoordinate(16, 9,
        "/areas/tol-dhurath/forest-2/16x9.c", "path");
    setCoordinate(17, 0,
        "/areas/tol-dhurath/forest-2/17x0.c", "path");
    setCoordinate(17, 1,
        "/areas/tol-dhurath/forest-2/17x1.c", "room");
    setCoordinate(17, 3,
        "/areas/tol-dhurath/forest-2/17x3.c", "path");
    setCoordinate(17, 4,
        "/areas/tol-dhurath/forest-2/17x4.c", "path");
    setCoordinate(17, 5,
        "/areas/tol-dhurath/forest-2/17x5.c", "path");
    setCoordinate(17, 6,
        "/areas/tol-dhurath/forest-2/17x6.c", "path");
    setCoordinate(17, 7,
        "/areas/tol-dhurath/forest-2/17x7.c", "path");
    setCoordinate(18, 0,
        "/areas/tol-dhurath/forest-2/18x0.c", "room");
    setCoordinate(18, 1,
        "/areas/tol-dhurath/forest-2/18x1.c", "path");
    setCoordinate(18, 3,
        "/areas/tol-dhurath/forest-2/18x3.c", "room");
    setCoordinate(18, 6,
        "/areas/tol-dhurath/forest-2/18x6.c", "path");
    setCoordinate(18, 7,
        "/areas/tol-dhurath/forest-2/18x7.c", "path");
    setCoordinate(19, 0,
        "/areas/tol-dhurath/forest-2/19x0.c", "room");
    setCoordinate(19, 1,
        "/areas/tol-dhurath/forest-2/19x1.c", "path");
    setCoordinate(19, 2,
        "/areas/tol-dhurath/forest-2/19x2.c", "path");
    setCoordinate(19, 3,
        "/areas/tol-dhurath/forest-2/19x3.c", "path");
    setCoordinate(19, 4,
        "/areas/tol-dhurath/forest-2/19x4.c", "path");
    setCoordinate(19, 5,
        "/areas/tol-dhurath/forest-2/19x5.c", "path");
    setCoordinate(19, 6,
        "/areas/tol-dhurath/forest-2/19x6.c", "path");
    setCoordinate(19, 7,
        "/areas/tol-dhurath/forest-2/19x7.c", "path");
    setCoordinate(19, 8,
        "/areas/tol-dhurath/forest-2/19x8.c", "path");
    setCoordinate(19, 9,
        "/areas/tol-dhurath/forest-2/19x9.c", "room");
    setCoordinate(1, 0,
        "/areas/tol-dhurath/forest-2/1x0.c", "room");
    setCoordinate(1, 1,
        "/areas/tol-dhurath/forest-2/1x1.c", "path");
    setCoordinate(1, 2,
        "/areas/tol-dhurath/forest-2/1x2.c", "path");
    setCoordinate(1, 3,
        "/areas/tol-dhurath/forest-2/1x3.c", "path");
    setCoordinate(1, 4,
        "/areas/tol-dhurath/forest-2/1x4.c", "path");
    setCoordinate(1, 5,
        "/areas/tol-dhurath/forest-2/1x5.c", "room");
    setCoordinate(1, 6,
        "/areas/tol-dhurath/forest-2/1x6.c", "path");
    setCoordinate(1, 7,
        "/areas/tol-dhurath/forest-2/1x7.c", "room");
    setCoordinate(1, 8,
        "/areas/tol-dhurath/forest-2/1x8.c", "path");
    setCoordinate(20, 0,
        "/areas/tol-dhurath/forest-2/20x0.c", "path");
    setCoordinate(20, 1,
        "/areas/tol-dhurath/forest-2/20x1.c", "path");
    setCoordinate(20, 3,
        "/areas/tol-dhurath/forest-2/20x3.c", "path");
    setCoordinate(20, 4,
        "/areas/tol-dhurath/forest-2/20x4.c", "room");
    setCoordinate(20, 5,
        "/areas/tol-dhurath/forest-2/20x5.c", "path");
    setCoordinate(20, 6,
        "/areas/tol-dhurath/forest-2/20x6.c", "path");
    setCoordinate(20, 7,
        "/areas/tol-dhurath/forest-2/20x7.c", "room");
    setCoordinate(20, 8,
        "/areas/tol-dhurath/forest-2/20x8.c", "room");
    setCoordinate(21, 0,
        "/areas/tol-dhurath/forest-2/21x0.c", "room");
    setCoordinate(21, 2,
        "/areas/tol-dhurath/forest-2/21x2.c", "path");
    setCoordinate(21, 3,
        "/areas/tol-dhurath/forest-2/21x3.c", "path");
    setCoordinate(21, 4,
        "/areas/tol-dhurath/forest-2/21x4.c", "path");
    setCoordinate(21, 5,
        "/areas/tol-dhurath/forest-2/21x5.c", "path");
    setCoordinate(21, 6,
        "/areas/tol-dhurath/forest-2/21x6.c", "path");
    setCoordinate(22, 2,
        "/areas/tol-dhurath/forest-2/22x2.c", "path");
    setCoordinate(22, 3,
        "/areas/tol-dhurath/forest-2/22x3.c", "path");
    setCoordinate(22, 4,
        "/areas/tol-dhurath/forest-2/22x4.c", "room");
    setCoordinate(22, 5,
        "/areas/tol-dhurath/forest-2/22x5.c", "path");
    setCoordinate(22, 6,
        "/areas/tol-dhurath/forest-2/22x6.c", "room");
    setCoordinate(23, 2,
        "/areas/tol-dhurath/forest-2/23x2.c", "room");
    setCoordinate(23, 5,
        "/areas/tol-dhurath/forest-2/23x5.c", "path");
    setCoordinate(23, 6,
        "/areas/tol-dhurath/forest-2/23x6.c", "path");
    setCoordinate(23, 7,
        "/areas/tol-dhurath/forest-2/23x7.c", "room");
    setCoordinate(24, 5,
        "/areas/tol-dhurath/forest-2/24x5.c", "path");
    setCoordinate(24, 6,
        "/areas/tol-dhurath/forest-2/24x6.c", "exit");
    setCoordinate(24, 7,
        "/areas/tol-dhurath/forest-2/24x7.c", "room");
    setCoordinate(2, 1,
        "/areas/tol-dhurath/forest-2/2x1.c", "path");
    setCoordinate(2, 2,
        "/areas/tol-dhurath/forest-2/2x2.c", "path");
    setCoordinate(2, 3,
        "/areas/tol-dhurath/forest-2/2x3.c", "room");
    setCoordinate(2, 4,
        "/areas/tol-dhurath/forest-2/2x4.c", "path");
    setCoordinate(2, 5,
        "/areas/tol-dhurath/forest-2/2x5.c", "path");
    setCoordinate(2, 6,
        "/areas/tol-dhurath/forest-2/2x6.c", "path");
    setCoordinate(2, 8,
        "/areas/tol-dhurath/forest-2/2x8.c", "room");
    setCoordinate(3, 0,
        "/areas/tol-dhurath/forest-2/3x0.c", "path");
    setCoordinate(3, 1,
        "/areas/tol-dhurath/forest-2/3x1.c", "path");
    setCoordinate(3, 2,
        "/areas/tol-dhurath/forest-2/3x2.c", "room");
    setCoordinate(3, 3,
        "/areas/tol-dhurath/forest-2/3x3.c", "room");
    setCoordinate(3, 4,
        "/areas/tol-dhurath/forest-2/3x4.c", "path");
    setCoordinate(3, 5,
        "/areas/tol-dhurath/forest-2/3x5.c", "path");
    setCoordinate(3, 6,
        "/areas/tol-dhurath/forest-2/3x6.c", "path");
    setCoordinate(4, 0,
        "/areas/tol-dhurath/forest-2/4x0.c", "path");
    setCoordinate(4, 1,
        "/areas/tol-dhurath/forest-2/4x1.c", "path");
    setCoordinate(4, 4,
        "/areas/tol-dhurath/forest-2/4x4.c", "path");
    setCoordinate(4, 5,
        "/areas/tol-dhurath/forest-2/4x5.c", "room");
    setCoordinate(4, 6,
        "/areas/tol-dhurath/forest-2/4x6.c", "path");
    setCoordinate(4, 7,
        "/areas/tol-dhurath/forest-2/4x7.c", "path");
    setCoordinate(4, 8,
        "/areas/tol-dhurath/forest-2/4x8.c", "path");
    setCoordinate(5, 0,
        "/areas/tol-dhurath/forest-2/5x0.c", "path");
    setCoordinate(5, 1,
        "/areas/tol-dhurath/forest-2/5x1.c", "room");
    setCoordinate(5, 2,
        "/areas/tol-dhurath/forest-2/5x2.c", "room");
    setCoordinate(5, 7,
        "/areas/tol-dhurath/forest-2/5x7.c", "room");
    setCoordinate(5, 8,
        "/areas/tol-dhurath/forest-2/5x8.c", "room");
    setCoordinate(5, 9,
        "/areas/tol-dhurath/forest-2/5x9.c", "path");
    setCoordinate(6, 0,
        "/areas/tol-dhurath/forest-2/6x0.c", "room");
    setCoordinate(6, 1,
        "/areas/tol-dhurath/forest-2/6x1.c", "path");
    setCoordinate(6, 2,
        "/areas/tol-dhurath/forest-2/6x2.c", "path");
    setCoordinate(6, 9,
        "/areas/tol-dhurath/forest-2/6x9.c", "path");
    setCoordinate(7, 1,
        "/areas/tol-dhurath/forest-2/7x1.c", "path");
    setCoordinate(7, 2,
        "/areas/tol-dhurath/forest-2/7x2.c", "path");
    setCoordinate(7, 3,
        "/areas/tol-dhurath/forest-2/7x3.c", "room");
    setCoordinate(7, 9,
        "/areas/tol-dhurath/forest-2/7x9.c", "path");
    setCoordinate(8, 0,
        "/areas/tol-dhurath/forest-2/8x0.c", "room");
    setCoordinate(8, 1,
        "/areas/tol-dhurath/forest-2/8x1.c", "path");
    setCoordinate(8, 2,
        "/areas/tol-dhurath/forest-2/8x2.c", "path");
    setCoordinate(8, 3,
        "/areas/tol-dhurath/forest-2/8x3.c", "path");
    setCoordinate(8, 8,
        "/areas/tol-dhurath/forest-2/8x8.c", "room");
    setCoordinate(8, 9,
        "/areas/tol-dhurath/forest-2/8x9.c", "path");
    setCoordinate(9, 1,
        "/areas/tol-dhurath/forest-2/9x1.c", "path");
    setCoordinate(9, 3,
        "/areas/tol-dhurath/forest-2/9x3.c", "room");
    setCoordinate(9, 4,
        "/areas/tol-dhurath/forest-2/9x4.c", "path");
    setCoordinate(9, 8,
        "/areas/tol-dhurath/forest-2/9x8.c", "path");

    // MapIcons
}
