//*****************************************************************************
// Copyright (c) 2024 - Allen Cummings, RealmsMUD, All rights reserved. See
//                      the accompanying LICENSE file for details.
//*****************************************************************************
inherit "/lib/environment/region.c";

/////////////////////////////////////////////////////////////////////////////
public void Setup()
{
    setRegionName("Tol-Dhurath Forest 5");
    setRegionType("forest");
    setDimensions(25, 10);
    // EntryCoordinate
    setSettlementChance(-1);

    setCoordinate(0, 1,
        "/areas/tol-dhurath/forest-5/0x1.c", "entry");
    setCoordinate(0, 2,
        "/areas/tol-dhurath/forest-5/0x2.c", "path");
    setCoordinate(0, 3,
        "/areas/tol-dhurath/forest-5/0x3.c", "room");
    setCoordinate(0, 4,
        "/areas/tol-dhurath/forest-5/0x4.c", "path");
    setCoordinate(0, 5,
        "/areas/tol-dhurath/forest-5/0x5.c", "room");
    setCoordinate(0, 6,
        "/areas/tol-dhurath/forest-5/0x6.c", "path");
    setCoordinate(10, 0,
        "/areas/tol-dhurath/forest-5/10x0.c", "path");
    setCoordinate(10, 1,
        "/areas/tol-dhurath/forest-5/10x1.c", "path");
    setCoordinate(10, 4,
        "/areas/tol-dhurath/forest-5/10x4.c", "room");
    setCoordinate(10, 5,
        "/areas/tol-dhurath/forest-5/10x5.c", "room");
    setCoordinate(10, 7,
        "/areas/tol-dhurath/forest-5/10x7.c", "room");
    setCoordinate(10, 8,
        "/areas/tol-dhurath/forest-5/10x8.c", "room");
    setCoordinate(10, 9,
        "/areas/tol-dhurath/forest-5/10x9.c", "room");
    setCoordinate(11, 0,
        "/areas/tol-dhurath/forest-5/11x0.c", "room");
    setCoordinate(11, 1,
        "/areas/tol-dhurath/forest-5/11x1.c", "path");
    setCoordinate(11, 3,
        "/areas/tol-dhurath/forest-5/11x3.c", "room");
    setCoordinate(11, 6,
        "/areas/tol-dhurath/forest-5/11x6.c", "room");
    setCoordinate(11, 9,
        "/areas/tol-dhurath/forest-5/11x9.c", "path");
    setCoordinate(12, 3,
        "/areas/tol-dhurath/forest-5/12x3.c", "path");
    setCoordinate(12, 6,
        "/areas/tol-dhurath/forest-5/12x6.c", "path");
    setCoordinate(12, 9,
        "/areas/tol-dhurath/forest-5/12x9.c", "path");
    setCoordinate(13, 0,
        "/areas/tol-dhurath/forest-5/13x0.c", "path");
    setCoordinate(13, 1,
        "/areas/tol-dhurath/forest-5/13x1.c", "room");
    setCoordinate(13, 2,
        "/areas/tol-dhurath/forest-5/13x2.c", "path");
    setCoordinate(13, 3,
        "/areas/tol-dhurath/forest-5/13x3.c", "path");
    setCoordinate(13, 5,
        "/areas/tol-dhurath/forest-5/13x5.c", "path");
    setCoordinate(13, 6,
        "/areas/tol-dhurath/forest-5/13x6.c", "path");
    setCoordinate(13, 9,
        "/areas/tol-dhurath/forest-5/13x9.c", "path");
    setCoordinate(14, 0,
        "/areas/tol-dhurath/forest-5/14x0.c", "room");
    setCoordinate(14, 1,
        "/areas/tol-dhurath/forest-5/14x1.c", "path");
    setCoordinate(14, 2,
        "/areas/tol-dhurath/forest-5/14x2.c", "path");
    setCoordinate(14, 5,
        "/areas/tol-dhurath/forest-5/14x5.c", "path");
    setCoordinate(14, 6,
        "/areas/tol-dhurath/forest-5/14x6.c", "path");
    setCoordinate(14, 7,
        "/areas/tol-dhurath/forest-5/14x7.c", "path");
    setCoordinate(14, 8,
        "/areas/tol-dhurath/forest-5/14x8.c", "room");
    setCoordinate(14, 9,
        "/areas/tol-dhurath/forest-5/14x9.c", "path");
    setCoordinate(15, 2,
        "/areas/tol-dhurath/forest-5/15x2.c", "room");
    setCoordinate(15, 3,
        "/areas/tol-dhurath/forest-5/15x3.c", "room");
    setCoordinate(15, 4,
        "/areas/tol-dhurath/forest-5/15x4.c", "path");
    setCoordinate(15, 5,
        "/areas/tol-dhurath/forest-5/15x5.c", "path");
    setCoordinate(15, 6,
        "/areas/tol-dhurath/forest-5/15x6.c", "path");
    setCoordinate(15, 7,
        "/areas/tol-dhurath/forest-5/15x7.c", "room");
    setCoordinate(15, 9,
        "/areas/tol-dhurath/forest-5/15x9.c", "path");
    setCoordinate(16, 0,
        "/areas/tol-dhurath/forest-5/16x0.c", "path");
    setCoordinate(16, 1,
        "/areas/tol-dhurath/forest-5/16x1.c", "path");
    setCoordinate(16, 2,
        "/areas/tol-dhurath/forest-5/16x2.c", "path");
    setCoordinate(16, 3,
        "/areas/tol-dhurath/forest-5/16x3.c", "path");
    setCoordinate(16, 4,
        "/areas/tol-dhurath/forest-5/16x4.c", "path");
    setCoordinate(16, 5,
        "/areas/tol-dhurath/forest-5/16x5.c", "room");
    setCoordinate(16, 9,
        "/areas/tol-dhurath/forest-5/16x9.c", "path");
    setCoordinate(17, 0,
        "/areas/tol-dhurath/forest-5/17x0.c", "path");
    setCoordinate(17, 5,
        "/areas/tol-dhurath/forest-5/17x5.c", "path");
    setCoordinate(17, 6,
        "/areas/tol-dhurath/forest-5/17x6.c", "path");
    setCoordinate(17, 9,
        "/areas/tol-dhurath/forest-5/17x9.c", "path");
    setCoordinate(18, 0,
        "/areas/tol-dhurath/forest-5/18x0.c", "path");
    setCoordinate(18, 1,
        "/areas/tol-dhurath/forest-5/18x1.c", "path");
    setCoordinate(18, 3,
        "/areas/tol-dhurath/forest-5/18x3.c", "path");
    setCoordinate(18, 4,
        "/areas/tol-dhurath/forest-5/18x4.c", "room");
    setCoordinate(18, 5,
        "/areas/tol-dhurath/forest-5/18x5.c", "room");
    setCoordinate(18, 6,
        "/areas/tol-dhurath/forest-5/18x6.c", "path");
    setCoordinate(18, 7,
        "/areas/tol-dhurath/forest-5/18x7.c", "path");
    setCoordinate(18, 9,
        "/areas/tol-dhurath/forest-5/18x9.c", "path");
    setCoordinate(19, 1,
        "/areas/tol-dhurath/forest-5/19x1.c", "path");
    setCoordinate(19, 2,
        "/areas/tol-dhurath/forest-5/19x2.c", "path");
    setCoordinate(19, 3,
        "/areas/tol-dhurath/forest-5/19x3.c", "path");
    setCoordinate(19, 4,
        "/areas/tol-dhurath/forest-5/19x4.c", "room");
    setCoordinate(19, 5,
        "/areas/tol-dhurath/forest-5/19x5.c", "path");
    setCoordinate(19, 7,
        "/areas/tol-dhurath/forest-5/19x7.c", "room");
    setCoordinate(19, 8,
        "/areas/tol-dhurath/forest-5/19x8.c", "path");
    setCoordinate(19, 9,
        "/areas/tol-dhurath/forest-5/19x9.c", "room");
    setCoordinate(1, 1,
        "/areas/tol-dhurath/forest-5/1x1.c", "path");
    setCoordinate(1, 2,
        "/areas/tol-dhurath/forest-5/1x2.c", "room");
    setCoordinate(1, 3,
        "/areas/tol-dhurath/forest-5/1x3.c", "path");
    setCoordinate(1, 4,
        "/areas/tol-dhurath/forest-5/1x4.c", "path");
    setCoordinate(1, 6,
        "/areas/tol-dhurath/forest-5/1x6.c", "path");
    setCoordinate(1, 7,
        "/areas/tol-dhurath/forest-5/1x7.c", "path");
    setCoordinate(1, 8,
        "/areas/tol-dhurath/forest-5/1x8.c", "path");
    setCoordinate(1, 9,
        "/areas/tol-dhurath/forest-5/1x9.c", "path");
    setCoordinate(20, 0,
        "/areas/tol-dhurath/forest-5/20x0.c", "room");
    setCoordinate(20, 1,
        "/areas/tol-dhurath/forest-5/20x1.c", "room");
    setCoordinate(20, 2,
        "/areas/tol-dhurath/forest-5/20x2.c", "path");
    setCoordinate(20, 4,
        "/areas/tol-dhurath/forest-5/20x4.c", "path");
    setCoordinate(20, 5,
        "/areas/tol-dhurath/forest-5/20x5.c", "path");
    setCoordinate(20, 8,
        "/areas/tol-dhurath/forest-5/20x8.c", "path");
    setCoordinate(21, 2,
        "/areas/tol-dhurath/forest-5/21x2.c", "path");
    setCoordinate(21, 3,
        "/areas/tol-dhurath/forest-5/21x3.c", "room");
    setCoordinate(21, 4,
        "/areas/tol-dhurath/forest-5/21x4.c", "path");
    setCoordinate(21, 5,
        "/areas/tol-dhurath/forest-5/21x5.c", "path");
    setCoordinate(21, 7,
        "/areas/tol-dhurath/forest-5/21x7.c", "room");
    setCoordinate(21, 8,
        "/areas/tol-dhurath/forest-5/21x8.c", "path");
    setCoordinate(22, 4,
        "/areas/tol-dhurath/forest-5/22x4.c", "room");
    setCoordinate(22, 5,
        "/areas/tol-dhurath/forest-5/22x5.c", "path");
    setCoordinate(22, 6,
        "/areas/tol-dhurath/forest-5/22x6.c", "room");
    setCoordinate(23, 3,
        "/areas/tol-dhurath/forest-5/23x3.c", "path");
    setCoordinate(23, 4,
        "/areas/tol-dhurath/forest-5/23x4.c", "path");
    setCoordinate(23, 6,
        "/areas/tol-dhurath/forest-5/23x6.c", "room");
    setCoordinate(23, 7,
        "/areas/tol-dhurath/forest-5/23x7.c", "room");
    setCoordinate(24, 3,
        "/areas/tol-dhurath/forest-5/24x3.c", "room");
    setCoordinate(24, 4,
        "/areas/tol-dhurath/forest-5/24x4.c", "room");
    setCoordinate(24, 5,
        "/areas/tol-dhurath/forest-5/24x5.c", "exit");
    setCoordinate(24, 6,
        "/areas/tol-dhurath/forest-5/24x6.c", "room");
    setCoordinate(24, 7,
        "/areas/tol-dhurath/forest-5/24x7.c", "path");
    setCoordinate(2, 0,
        "/areas/tol-dhurath/forest-5/2x0.c", "room");
    setCoordinate(2, 1,
        "/areas/tol-dhurath/forest-5/2x1.c", "path");
    setCoordinate(2, 2,
        "/areas/tol-dhurath/forest-5/2x2.c", "path");
    setCoordinate(2, 3,
        "/areas/tol-dhurath/forest-5/2x3.c", "path");
    setCoordinate(2, 4,
        "/areas/tol-dhurath/forest-5/2x4.c", "path");
    setCoordinate(2, 7,
        "/areas/tol-dhurath/forest-5/2x7.c", "path");
    setCoordinate(2, 8,
        "/areas/tol-dhurath/forest-5/2x8.c", "path");
    setCoordinate(2, 9,
        "/areas/tol-dhurath/forest-5/2x9.c", "path");
    setCoordinate(3, 0,
        "/areas/tol-dhurath/forest-5/3x0.c", "path");
    setCoordinate(3, 1,
        "/areas/tol-dhurath/forest-5/3x1.c", "path");
    setCoordinate(3, 2,
        "/areas/tol-dhurath/forest-5/3x2.c", "room");
    setCoordinate(3, 3,
        "/areas/tol-dhurath/forest-5/3x3.c", "path");
    setCoordinate(3, 4,
        "/areas/tol-dhurath/forest-5/3x4.c", "path");
    setCoordinate(3, 5,
        "/areas/tol-dhurath/forest-5/3x5.c", "path");
    setCoordinate(3, 6,
        "/areas/tol-dhurath/forest-5/3x6.c", "path");
    setCoordinate(3, 7,
        "/areas/tol-dhurath/forest-5/3x7.c", "room");
    setCoordinate(3, 8,
        "/areas/tol-dhurath/forest-5/3x8.c", "path");
    setCoordinate(3, 9,
        "/areas/tol-dhurath/forest-5/3x9.c", "path");
    setCoordinate(4, 0,
        "/areas/tol-dhurath/forest-5/4x0.c", "path");
    setCoordinate(4, 2,
        "/areas/tol-dhurath/forest-5/4x2.c", "path");
    setCoordinate(4, 3,
        "/areas/tol-dhurath/forest-5/4x3.c", "path");
    setCoordinate(4, 4,
        "/areas/tol-dhurath/forest-5/4x4.c", "path");
    setCoordinate(4, 5,
        "/areas/tol-dhurath/forest-5/4x5.c", "room");
    setCoordinate(4, 6,
        "/areas/tol-dhurath/forest-5/4x6.c", "path");
    setCoordinate(5, 0,
        "/areas/tol-dhurath/forest-5/5x0.c", "room");
    setCoordinate(5, 1,
        "/areas/tol-dhurath/forest-5/5x1.c", "path");
    setCoordinate(5, 2,
        "/areas/tol-dhurath/forest-5/5x2.c", "path");
    setCoordinate(5, 4,
        "/areas/tol-dhurath/forest-5/5x4.c", "path");
    setCoordinate(5, 6,
        "/areas/tol-dhurath/forest-5/5x6.c", "room");
    setCoordinate(5, 7,
        "/areas/tol-dhurath/forest-5/5x7.c", "path");
    setCoordinate(6, 0,
        "/areas/tol-dhurath/forest-5/6x0.c", "path");
    setCoordinate(6, 1,
        "/areas/tol-dhurath/forest-5/6x1.c", "path");
    setCoordinate(6, 4,
        "/areas/tol-dhurath/forest-5/6x4.c", "path");
    setCoordinate(6, 7,
        "/areas/tol-dhurath/forest-5/6x7.c", "path");
    setCoordinate(7, 0,
        "/areas/tol-dhurath/forest-5/7x0.c", "room");
    setCoordinate(7, 1,
        "/areas/tol-dhurath/forest-5/7x1.c", "room");
    setCoordinate(7, 3,
        "/areas/tol-dhurath/forest-5/7x3.c", "room");
    setCoordinate(7, 4,
        "/areas/tol-dhurath/forest-5/7x4.c", "path");
    setCoordinate(7, 5,
        "/areas/tol-dhurath/forest-5/7x5.c", "path");
    setCoordinate(7, 6,
        "/areas/tol-dhurath/forest-5/7x6.c", "path");
    setCoordinate(7, 7,
        "/areas/tol-dhurath/forest-5/7x7.c", "path");
    setCoordinate(8, 0,
        "/areas/tol-dhurath/forest-5/8x0.c", "path");
    setCoordinate(8, 1,
        "/areas/tol-dhurath/forest-5/8x1.c", "path");
    setCoordinate(8, 3,
        "/areas/tol-dhurath/forest-5/8x3.c", "path");
    setCoordinate(8, 4,
        "/areas/tol-dhurath/forest-5/8x4.c", "path");
    setCoordinate(8, 5,
        "/areas/tol-dhurath/forest-5/8x5.c", "path");
    setCoordinate(8, 6,
        "/areas/tol-dhurath/forest-5/8x6.c", "path");
    setCoordinate(8, 7,
        "/areas/tol-dhurath/forest-5/8x7.c", "path");
    setCoordinate(8, 8,
        "/areas/tol-dhurath/forest-5/8x8.c", "path");
    setCoordinate(8, 9,
        "/areas/tol-dhurath/forest-5/8x9.c", "path");
    setCoordinate(9, 0,
        "/areas/tol-dhurath/forest-5/9x0.c", "path");
    setCoordinate(9, 1,
        "/areas/tol-dhurath/forest-5/9x1.c", "room");
    setCoordinate(9, 3,
        "/areas/tol-dhurath/forest-5/9x3.c", "room");
    setCoordinate(9, 5,
        "/areas/tol-dhurath/forest-5/9x5.c", "path");
    setCoordinate(9, 8,
        "/areas/tol-dhurath/forest-5/9x8.c", "path");
    setCoordinate(9, 9,
        "/areas/tol-dhurath/forest-5/9x9.c", "path");

    // MapIcons
}
