# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container:
  image: corelib/realms-lib
  endpoint: 'Realms Registry'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
