# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container:
  image: corelib/realms-lib
  endpoint: 'Realms Registry'

steps:
- bash: mv -f /mud/* /__w/1/s/; rm -rf /mud; ln -s /__w/1/s /mud; /prepSimulEfun; /configureBuild
  displayName: 'Build pre-processing'

- bash: /compiler/src/ldmud
  displayName: 'Executing Build'
