# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container:
  image: corelib/realms-lib
  endpoint: 'Realms Registry'

steps:
- bash: cp -r /mud/lib/* /__w/1/s; rm -rf /mud/lib; ln -s /__w/1/s /mud/lib; ls -la /mud/lib; /prepSimulEfun; /configureBuild
  displayName: 'Build pre-processing'

- bash: /compiler/src/ldmud
  displayName: 'Executing Build'
