# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

continueOnError: true 

pool:
  vmImage: 'ubuntu-latest'

container:
  image: corelib/realms-lib
  endpoint: 'Realms Registry'

steps:
- bash: cp -r /mud/lib/* $(Build.SourcesDirectory); 
        rm -rf /mud/lib; 
        ln -s $(Build.SourcesDirectory) /mud/lib; 
        cp $(Build.SourcesDirectory)/secure/simul_efun.c $(Build.SourcesDirectory)/secure/simul_efun.orig; 
        cp $(Build.SourcesDirectory)/secure/master/preload.c $(Build.SourcesDirectory)/secure/master/preload.orig; 
        cp $(Build.SourcesDirectory)/init/init_file $(Build.SourcesDirectory)/init/init_file.orig; 
        /prepSimulEfun; 
        /configureBuild
  displayName: 'Build pre-processing'

- bash: service mysql start; /create_db.pl
  displayName: 'Setting up the database'

- bash: 
        mkdir $(Build.ArtifactStagingDirectory)/reports
  displayName: 'Building Library'

- bash: /executeTests $(Build.SourcesDirectory) $(Build.ArtifactStagingDirectory)/reports
  displayName: 'Executing Tests'

- bash: rm -rf /mud/lib/players/* 
               /mud/lib/brokenFile.c 
               /mud/lib/include 
               /mud/lib/README.md 
               /mud/lib/git*
               /mud/lib/*.log 
               /mud/lib/demo-videos;
        mv /mud/lib/secure/simul_efun.orig /mud/lib/secure/simul_efun.c;
        mv /mud/lib/secure/master/preload.orig /mud/lib/secure/master/preload.c; 
        mv /mud/lib/init/init_file.orig /mud/lib/init/init_file;
        mkdir $(Build.ArtifactStagingDirectory)/mudlib;
        cp -a /mud/lib/* $(Build.ArtifactStagingDirectory)/mudlib
  displayName: 'Packaging Library'

- task: PublishBuildArtifacts@1
  displayName: Publishing Test Reports
