//*****************************************************************************
// Copyright (c) 2025 - Allen Cummings, RealmsMUD, All rights reserved. See
//                      the accompanying LICENSE file for details.
//*****************************************************************************
inherit "/lib/environment/region.c";

/////////////////////////////////////////////////////////////////////////////
public void Setup()
{
    setRegionName("Tol-Dhurath Temple, Main Level");
    setRegionType("tol-dhurath");
    setDimensions(20, 10);

    setCoordinate(0, 0,
        "/areas/tol-dhurath/temple-interior/0x0.c", "none");
    setCoordinate(0, 1,
        "/areas/tol-dhurath/temple-interior/0x1.c", "none");
    setCoordinate(0, 2,
        "/areas/tol-dhurath/temple-interior/0x2.c", "none");
    setCoordinate(0, 3,
        "/areas/tol-dhurath/temple-interior/0x3.c", "none");
    setCoordinate(0, 4,
        "/areas/tol-dhurath/temple-interior/0x4.c", "none");
    setCoordinate(1, 0,
        "/areas/tol-dhurath/temple-interior/1x0.c", "none");
    setCoordinate(1, 1,
        "/areas/tol-dhurath/temple-interior/1x1.c", "none");
    setCoordinate(1, 2,
        "/areas/tol-dhurath/temple-interior/1x2.c", "none");
    setCoordinate(1, 3,
        "/areas/tol-dhurath/temple-interior/1x3.c", "none");
    setCoordinate(1, 4,
        "/areas/tol-dhurath/temple-interior/1x4.c", "none");
    setCoordinate(2, 0,
        "/areas/tol-dhurath/temple-interior/2x0.c", "none");
    setCoordinate(2, 1,
        "/areas/tol-dhurath/temple-interior/2x1.c", "none");
    setCoordinate(2, 2,
        "/areas/tol-dhurath/temple-interior/2x2.c", "none");
    setCoordinate(2, 3,
        "/areas/tol-dhurath/temple-interior/2x3.c", "none");
    setCoordinate(2, 4,
        "/areas/tol-dhurath/temple-interior/2x4.c", "none");
    setCoordinate(3, 0,
        "/areas/tol-dhurath/temple-interior/3x0.c", "none");
    setCoordinate(3, 1,
        "/areas/tol-dhurath/temple-interior/3x1.c", "none");
    setCoordinate(3, 2,
        "/areas/tol-dhurath/temple-interior/3x2.c", "none");
    setCoordinate(3, 3,
        "/areas/tol-dhurath/temple-interior/3x3.c", "none");
    setCoordinate(3, 4,
        "/areas/tol-dhurath/temple-interior/3x4.c", "none");
    setCoordinate(3, 5,
        "/areas/tol-dhurath/temple-interior/3x5.c", "none");
    setCoordinate(3, 6,
        "/areas/tol-dhurath/temple-interior/3x6.c", "none");
    setCoordinate(3, 7,
        "/areas/tol-dhurath/temple-interior/3x7.c", "none");
    setCoordinate(3, 8,
        "/areas/tol-dhurath/temple-interior/3x8.c", "none");
    setCoordinate(3, 9,
        "/areas/tol-dhurath/temple-interior/3x9.c", "none");
    setCoordinate(4, 0,
        "/areas/tol-dhurath/temple-interior/4x0.c", "none");
    setCoordinate(4, 1,
        "/areas/tol-dhurath/temple-interior/4x1.c", "none");
    setCoordinate(4, 2,
        "/areas/tol-dhurath/temple-interior/4x2.c", "none");
    setCoordinate(4, 3,
        "/areas/tol-dhurath/temple-interior/4x3.c", "none");
    setCoordinate(4, 4,
        "/areas/tol-dhurath/temple-interior/4x4.c", "none");
    setCoordinate(4, 5,
        "/areas/tol-dhurath/temple-interior/4x5.c", "none");
    setCoordinate(4, 6,
        "/areas/tol-dhurath/temple-interior/4x6.c", "none");
    setCoordinate(4, 7,
        "/areas/tol-dhurath/temple-interior/4x7.c", "none");
    setCoordinate(4, 8,
        "/areas/tol-dhurath/temple-interior/4x8.c", "none");
    setCoordinate(4, 9,
        "/areas/tol-dhurath/temple-interior/4x9.c", "none");
    setCoordinate(5, 0,
        "/areas/tol-dhurath/temple-interior/5x0.c", "none");
    setCoordinate(5, 1,
        "/areas/tol-dhurath/temple-interior/5x1.c", "none");
    setCoordinate(5, 2,
        "/areas/tol-dhurath/temple-interior/5x2.c", "none");
    setCoordinate(5, 3,
        "/areas/tol-dhurath/temple-interior/5x3.c", "none");
    setCoordinate(5, 4,
        "/areas/tol-dhurath/temple-interior/5x4.c", "none");
    setCoordinate(5, 5,
        "/areas/tol-dhurath/temple-interior/5x5.c", "none");
    setCoordinate(5, 6,
        "/areas/tol-dhurath/temple-interior/5x6.c", "none");
    setCoordinate(5, 7,
        "/areas/tol-dhurath/temple-interior/5x7.c", "none");
    setCoordinate(5, 8,
        "/areas/tol-dhurath/temple-interior/5x8.c", "none");
    setCoordinate(5, 9,
        "/areas/tol-dhurath/temple-interior/5x9.c", "none");
    setCoordinate(6, 0,
        "/areas/tol-dhurath/temple-interior/6x0.c", "none");
    setCoordinate(6, 1,
        "/areas/tol-dhurath/temple-interior/6x1.c", "none");
    setCoordinate(6, 2,
        "/areas/tol-dhurath/temple-interior/6x2.c", "none");
    setCoordinate(6, 3,
        "/areas/tol-dhurath/temple-interior/6x3.c", "none");
    setCoordinate(6, 4,
        "/areas/tol-dhurath/temple-interior/6x4.c", "none");
    setCoordinate(6, 5,
        "/areas/tol-dhurath/temple-interior/6x5.c", "none");
    setCoordinate(6, 6,
        "/areas/tol-dhurath/temple-interior/6x6.c", "none");
    setCoordinate(6, 7,
        "/areas/tol-dhurath/temple-interior/6x7.c", "none");
    setCoordinate(6, 8,
        "/areas/tol-dhurath/temple-interior/6x8.c", "none");
    setCoordinate(6, 9,
        "/areas/tol-dhurath/temple-interior/6x9.c", "none");
    setCoordinate(7, 2,
        "/areas/tol-dhurath/temple-interior/7x2.c", "none");
    setCoordinate(7, 3,
        "/areas/tol-dhurath/temple-interior/7x3.c", "none");
    setCoordinate(7, 4,
        "/areas/tol-dhurath/temple-interior/7x4.c", "none");
    setCoordinate(7, 5,
        "/areas/tol-dhurath/temple-interior/7x5.c", "none");
    setCoordinate(7, 6,
        "/areas/tol-dhurath/temple-interior/7x6.c", "none");
    setCoordinate(7, 7,
        "/areas/tol-dhurath/temple-interior/7x7.c", "none");
    setCoordinate(7, 8,
        "/areas/tol-dhurath/temple-interior/7x8.c", "none");
    setCoordinate(7, 9,
        "/areas/tol-dhurath/temple-interior/7x9.c", "none");
    setCoordinate(8, 0,
        "/areas/tol-dhurath/temple-interior/8x0.c", "none");
    setCoordinate(8, 1,
        "/areas/tol-dhurath/temple-interior/8x1.c", "none");
    setCoordinate(8, 2,
        "/areas/tol-dhurath/temple-interior/8x2.c", "none");
    setCoordinate(8, 3,
        "/areas/tol-dhurath/temple-interior/8x3.c", "none");
    setCoordinate(8, 4,
        "/areas/tol-dhurath/temple-interior/8x4.c", "none");
    setCoordinate(8, 5,
        "/areas/tol-dhurath/temple-interior/8x5.c", "none");
    setCoordinate(8, 6,
        "/areas/tol-dhurath/temple-interior/8x6.c", "none");
    setCoordinate(8, 7,
        "/areas/tol-dhurath/temple-interior/8x7.c", "none");
    setCoordinate(8, 8,
        "/areas/tol-dhurath/temple-interior/8x8.c", "none");
    setCoordinate(8, 9,
        "/areas/tol-dhurath/temple-interior/8x9.c", "none");
    setCoordinate(9, 0,
        "/areas/tol-dhurath/temple-interior/9x0.c", "none");
    setCoordinate(9, 1,
        "/areas/tol-dhurath/temple-interior/9x1.c", "none");
    setCoordinate(9, 2,
        "/areas/tol-dhurath/temple-interior/9x2.c", "none");
    setCoordinate(9, 3,
        "/areas/tol-dhurath/temple-interior/9x3.c", "none");
    setCoordinate(9, 4,
        "/areas/tol-dhurath/temple-interior/9x4.c", "none");
    setCoordinate(9, 5,
        "/areas/tol-dhurath/temple-interior/9x5.c", "none");
    setCoordinate(9, 6,
        "/areas/tol-dhurath/temple-interior/9x6.c", "none");
    setCoordinate(9, 7,
        "/areas/tol-dhurath/temple-interior/9x7.c", "none");
    setCoordinate(9, 8,
        "/areas/tol-dhurath/temple-interior/9x8.c", "none");
    setCoordinate(9, 9,
        "/areas/tol-dhurath/temple-interior/9x9.c", "none");
    setCoordinate(10, 0,
        "/areas/tol-dhurath/temple-interior/10x0.c", "none");
    setCoordinate(10, 1,
        "/areas/tol-dhurath/temple-interior/10x1.c", "none");
    setCoordinate(10, 2,
        "/areas/tol-dhurath/temple-interior/10x2.c", "none");
    setCoordinate(10, 3,
        "/areas/tol-dhurath/temple-interior/10x3.c", "none");
    setCoordinate(10, 4,
        "/areas/tol-dhurath/temple-interior/10x4.c", "none");
    setCoordinate(10, 5,
        "/areas/tol-dhurath/temple-interior/10x5.c", "none");
    setCoordinate(10, 6,
        "/areas/tol-dhurath/temple-interior/10x6.c", "none");
    setCoordinate(10, 7,
        "/areas/tol-dhurath/temple-interior/10x7.c", "none");
    setCoordinate(10, 8,
        "/areas/tol-dhurath/temple-interior/10x8.c", "none");
    setCoordinate(10, 9,
        "/areas/tol-dhurath/temple-interior/10x9.c", "none");
    setCoordinate(11, 0,
        "/areas/tol-dhurath/temple-interior/11x0.c", "none");
    setCoordinate(11, 1,
        "/areas/tol-dhurath/temple-interior/11x1.c", "none");
    setCoordinate(11, 2,
        "/areas/tol-dhurath/temple-interior/11x2.c", "none");
    setCoordinate(11, 3,
        "/areas/tol-dhurath/temple-interior/11x3.c", "none");
    setCoordinate(11, 4,
        "/areas/tol-dhurath/temple-interior/11x4.c", "none");
    setCoordinate(11, 5,
        "/areas/tol-dhurath/temple-interior/11x5.c", "none");
    setCoordinate(11, 6,
        "/areas/tol-dhurath/temple-interior/11x6.c", "none");
    setCoordinate(11, 7,
        "/areas/tol-dhurath/temple-interior/11x7.c", "none");
    setCoordinate(11, 8,
        "/areas/tol-dhurath/temple-interior/11x8.c", "none");
    setCoordinate(11, 9,
        "/areas/tol-dhurath/temple-interior/11x9.c", "none");
    setCoordinate(12, 0,
        "/areas/tol-dhurath/temple-interior/12x0.c", "none");
    setCoordinate(12, 1,
        "/areas/tol-dhurath/temple-interior/12x1.c", "none");
    setCoordinate(12, 2,
        "/areas/tol-dhurath/temple-interior/12x2.c", "none");
    setCoordinate(12, 3,
        "/areas/tol-dhurath/temple-interior/12x3.c", "none");
    setCoordinate(13, 0,
        "/areas/tol-dhurath/temple-interior/13x0.c", "none");
    setCoordinate(13, 1,
        "/areas/tol-dhurath/temple-interior/13x1.c", "none");
    setCoordinate(13, 2,
        "/areas/tol-dhurath/temple-interior/13x2.c", "none");
    setCoordinate(13, 3,
        "/areas/tol-dhurath/temple-interior/13x3.c", "none");
    setCoordinate(14, 0,
        "/areas/tol-dhurath/temple-interior/14x0.c", "none");
    setCoordinate(14, 1,
        "/areas/tol-dhurath/temple-interior/14x1.c", "none");
    setCoordinate(14, 2,
        "/areas/tol-dhurath/temple-interior/14x2.c", "none");
    setCoordinate(14, 3,
        "/areas/tol-dhurath/temple-interior/14x3.c", "none");
    setCoordinate(15, 0,
        "/areas/tol-dhurath/temple-interior/15x0.c", "none");
    setCoordinate(15, 1,
        "/areas/tol-dhurath/temple-interior/15x1.c", "none");
    setCoordinate(15, 2,
        "/areas/tol-dhurath/temple-interior/15x2.c", "none");
    setCoordinate(15, 3,
        "/areas/tol-dhurath/temple-interior/15x3.c", "none");
    setCoordinate(16, 0,
        "/areas/tol-dhurath/temple-interior/16x0.c", "none");
    setCoordinate(16, 1,
        "/areas/tol-dhurath/temple-interior/16x1.c", "none");
    setCoordinate(16, 2,
        "/areas/tol-dhurath/temple-interior/16x2.c", "none");
    setCoordinate(16, 3,
        "/areas/tol-dhurath/temple-interior/16x3.c", "none");
    setCoordinate(17, 0,
        "/areas/tol-dhurath/temple-interior/17x0.c", "none");
    setCoordinate(17, 1,
        "/areas/tol-dhurath/temple-interior/17x1.c", "none");
    setCoordinate(17, 2,
        "/areas/tol-dhurath/temple-interior/17x2.c", "none");
    setCoordinate(17, 3,
        "/areas/tol-dhurath/temple-interior/17x3.c", "none");
    setCoordinate(18, 0,
        "/areas/tol-dhurath/temple-interior/18x0.c", "none");
    setCoordinate(18, 1,
        "/areas/tol-dhurath/temple-interior/18x1.c", "none");
    setCoordinate(18, 2,
        "/areas/tol-dhurath/temple-interior/18x2.c", "none");
    setCoordinate(18, 3,
        "/areas/tol-dhurath/temple-interior/18x3.c", "none");
    setCoordinate(19, 0,
        "/areas/tol-dhurath/temple-interior/19x0.c", "none");
    setCoordinate(19, 1,
        "/areas/tol-dhurath/temple-interior/19x1.c", "none");
    setCoordinate(19, 2,
        "/areas/tol-dhurath/temple-interior/19x2.c", "none");
    setCoordinate(19, 3,
        "/areas/tol-dhurath/temple-interior/19x3.c", "none");
}
