//*****************************************************************************
// Copyright (c) 2017-2026 - Allen Cummings, RealmsMUD, All rights reserved. See
//                      the accompanying LICENSE file for details.
//*****************************************************************************
inherit "/lib/environment/region.c";

/////////////////////////////////////////////////////////////////////////////
public void Setup()
{
    setRegionName("test");
    setRegionType("forest");
    setDimensions(25, 10);

    setSettlementChance(-1);

    setCoordinate(0, 0,
        "/lib/tests/support/pathfinding/0x0.c", "room");
    setCoordinate(0, 1,
        "/lib/tests/support/pathfinding/0x1.c", "path");
    setCoordinate(0, 2,
        "/lib/tests/support/pathfinding/0x2.c", "entry");
    setCoordinate(0, 3,
        "/lib/tests/support/pathfinding/0x3.c", "path");
    setCoordinate(10, 0,
        "/lib/tests/support/pathfinding/10x0.c", "room");
    setCoordinate(10, 2,
        "/lib/tests/support/pathfinding/10x2.c", "path");
    setCoordinate(10, 3,
        "/lib/tests/support/pathfinding/10x3.c", "room");
    setCoordinate(10, 4,
        "/lib/tests/support/pathfinding/10x4.c", "room");
    setCoordinate(10, 6,
        "/lib/tests/support/pathfinding/10x6.c", "path");
    setCoordinate(10, 7,
        "/lib/tests/support/pathfinding/10x7.c", "path");
    setCoordinate(10, 8,
        "/lib/tests/support/pathfinding/10x8.c", "room");
    setCoordinate(10, 9,
        "/lib/tests/support/pathfinding/10x9.c", "path");
    setCoordinate(11, 1,
        "/lib/tests/support/pathfinding/11x1.c", "path");
    setCoordinate(11, 2,
        "/lib/tests/support/pathfinding/11x2.c", "path");
    setCoordinate(11, 4,
        "/lib/tests/support/pathfinding/11x4.c", "path");
    setCoordinate(11, 5,
        "/lib/tests/support/pathfinding/11x5.c", "path");
    setCoordinate(11, 6,
        "/lib/tests/support/pathfinding/11x6.c", "path");
    setCoordinate(11, 7,
        "/lib/tests/support/pathfinding/11x7.c", "path");
    setCoordinate(11, 8,
        "/lib/tests/support/pathfinding/11x8.c", "path");
    setCoordinate(12, 0,
        "/lib/tests/support/pathfinding/12x0.c", "room");
    setCoordinate(12, 1,
        "/lib/tests/support/pathfinding/12x1.c", "path");
    setCoordinate(12, 4,
        "/lib/tests/support/pathfinding/12x4.c", "room");
    setCoordinate(12, 6,
        "/lib/tests/support/pathfinding/12x6.c", "path");
    setCoordinate(12, 7,
        "/lib/tests/support/pathfinding/12x7.c", "path");
    setCoordinate(12, 8,
        "/lib/tests/support/pathfinding/12x8.c", "room");
    setCoordinate(13, 6,
        "/lib/tests/support/pathfinding/13x6.c", "path");
    setCoordinate(13, 7,
        "/lib/tests/support/pathfinding/13x7.c", "path");
    setCoordinate(13, 8,
        "/lib/tests/support/pathfinding/13x8.c", "room");
    setCoordinate(13, 9,
        "/lib/tests/support/pathfinding/13x9.c", "path");
    setCoordinate(14, 1,
        "/lib/tests/support/pathfinding/14x1.c", "path");
    setCoordinate(14, 2,
        "/lib/tests/support/pathfinding/14x2.c", "room");
    setCoordinate(14, 5,
        "/lib/tests/support/pathfinding/14x5.c", "room");
    setCoordinate(14, 6,
        "/lib/tests/support/pathfinding/14x6.c", "room");
    setCoordinate(14, 7,
        "/lib/tests/support/pathfinding/14x7.c", "path");
    setCoordinate(14, 9,
        "/lib/tests/support/pathfinding/14x9.c", "room");
    setCoordinate(15, 1,
        "/lib/tests/support/pathfinding/15x1.c", "path");
    setCoordinate(15, 4,
        "/lib/tests/support/pathfinding/15x4.c", "path");
    setCoordinate(15, 5,
        "/lib/tests/support/pathfinding/15x5.c", "room");
    setCoordinate(15, 6,
        "/lib/tests/support/pathfinding/15x6.c", "path");
    setCoordinate(15, 7,
        "/lib/tests/support/pathfinding/15x7.c", "room");
    setCoordinate(15, 8,
        "/lib/tests/support/pathfinding/15x8.c", "room");
    setCoordinate(15, 9,
        "/lib/tests/support/pathfinding/15x9.c", "path");
    setCoordinate(16, 1,
        "/lib/tests/support/pathfinding/16x1.c", "room");
    setCoordinate(16, 4,
        "/lib/tests/support/pathfinding/16x4.c", "path");
    setCoordinate(16, 5,
        "/lib/tests/support/pathfinding/16x5.c", "room");
    setCoordinate(16, 9,
        "/lib/tests/support/pathfinding/16x9.c", "path");
    setCoordinate(17, 1,
        "/lib/tests/support/pathfinding/17x1.c", "path");
    setCoordinate(17, 5,
        "/lib/tests/support/pathfinding/17x5.c", "path");
    setCoordinate(17, 6,
        "/lib/tests/support/pathfinding/17x6.c", "path");
    setCoordinate(17, 7,
        "/lib/tests/support/pathfinding/17x7.c", "path");
    setCoordinate(17, 8,
        "/lib/tests/support/pathfinding/17x8.c", "room");
    setCoordinate(17, 9,
        "/lib/tests/support/pathfinding/17x9.c", "path");
    setCoordinate(18, 0,
        "/lib/tests/support/pathfinding/18x0.c", "path");
    setCoordinate(18, 1,
        "/lib/tests/support/pathfinding/18x1.c", "path");
    setCoordinate(18, 3,
        "/lib/tests/support/pathfinding/18x3.c", "room");
    setCoordinate(18, 4,
        "/lib/tests/support/pathfinding/18x4.c", "path");
    setCoordinate(18, 5,
        "/lib/tests/support/pathfinding/18x5.c", "path");
    setCoordinate(18, 7,
        "/lib/tests/support/pathfinding/18x7.c", "path");
    setCoordinate(18, 8,
        "/lib/tests/support/pathfinding/18x8.c", "path");
    setCoordinate(19, 0,
        "/lib/tests/support/pathfinding/19x0.c", "room");
    setCoordinate(19, 1,
        "/lib/tests/support/pathfinding/19x1.c", "path");
    setCoordinate(19, 2,
        "/lib/tests/support/pathfinding/19x2.c", "room");
    setCoordinate(19, 3,
        "/lib/tests/support/pathfinding/19x3.c", "path");
    setCoordinate(19, 4,
        "/lib/tests/support/pathfinding/19x4.c", "path");
    setCoordinate(19, 5,
        "/lib/tests/support/pathfinding/19x5.c", "room");
    setCoordinate(19, 6,
        "/lib/tests/support/pathfinding/19x6.c", "path");
    setCoordinate(19, 7,
        "/lib/tests/support/pathfinding/19x7.c", "path");
    setCoordinate(1, 1,
        "/lib/tests/support/pathfinding/1x1.c", "path");
    setCoordinate(1, 2,
        "/lib/tests/support/pathfinding/1x2.c", "path");
    setCoordinate(1, 3,
        "/lib/tests/support/pathfinding/1x3.c", "path");
    setCoordinate(1, 4,
        "/lib/tests/support/pathfinding/1x4.c", "path");
    setCoordinate(1, 5,
        "/lib/tests/support/pathfinding/1x5.c", "room");
    setCoordinate(1, 9,
        "/lib/tests/support/pathfinding/1x9.c", "room");
    setCoordinate(20, 0,
        "/lib/tests/support/pathfinding/20x0.c", "path");
    setCoordinate(20, 1,
        "/lib/tests/support/pathfinding/20x1.c", "path");
    setCoordinate(20, 2,
        "/lib/tests/support/pathfinding/20x2.c", "path");
    setCoordinate(20, 5,
        "/lib/tests/support/pathfinding/20x5.c", "path");
    setCoordinate(20, 6,
        "/lib/tests/support/pathfinding/20x6.c", "path");
    setCoordinate(20, 7,
        "/lib/tests/support/pathfinding/20x7.c", "room");
    setCoordinate(20, 8,
        "/lib/tests/support/pathfinding/20x8.c", "path");
    setCoordinate(21, 0,
        "/lib/tests/support/pathfinding/21x0.c", "path");
    setCoordinate(21, 2,
        "/lib/tests/support/pathfinding/21x2.c", "path");
    setCoordinate(21, 3,
        "/lib/tests/support/pathfinding/21x3.c", "room");
    setCoordinate(21, 5,
        "/lib/tests/support/pathfinding/21x5.c", "room");
    setCoordinate(21, 6,
        "/lib/tests/support/pathfinding/21x6.c", "path");
    setCoordinate(21, 8,
        "/lib/tests/support/pathfinding/21x8.c", "path");
    setCoordinate(21, 9,
        "/lib/tests/support/pathfinding/21x9.c", "path");
    setCoordinate(22, 0,
        "/lib/tests/support/pathfinding/22x0.c", "path");
    setCoordinate(22, 1,
        "/lib/tests/support/pathfinding/22x1.c", "path");
    setCoordinate(22, 3,
        "/lib/tests/support/pathfinding/22x3.c", "path");
    setCoordinate(22, 4,
        "/lib/tests/support/pathfinding/22x4.c", "room");
    setCoordinate(22, 5,
        "/lib/tests/support/pathfinding/22x5.c", "path");
    setCoordinate(22, 6,
        "/lib/tests/support/pathfinding/22x6.c", "room");
    setCoordinate(22, 8,
        "/lib/tests/support/pathfinding/22x8.c", "room");
    setCoordinate(22, 9,
        "/lib/tests/support/pathfinding/22x9.c", "room");
    setCoordinate(23, 0,
        "/lib/tests/support/pathfinding/23x0.c", "path");
    setCoordinate(23, 1,
        "/lib/tests/support/pathfinding/23x1.c", "room");
    setCoordinate(23, 3,
        "/lib/tests/support/pathfinding/23x3.c", "path");
    setCoordinate(23, 4,
        "/lib/tests/support/pathfinding/23x4.c", "path");
    setCoordinate(23, 5,
        "/lib/tests/support/pathfinding/23x5.c", "path");
    setCoordinate(23, 8,
        "/lib/tests/support/pathfinding/23x8.c", "path");
    setCoordinate(24, 0,
        "/lib/tests/support/pathfinding/24x0.c", "path");
    setCoordinate(24, 1,
        "/lib/tests/support/pathfinding/24x1.c", "room");
    setCoordinate(24, 2,
        "/lib/tests/support/pathfinding/24x2.c", "exit");
    setCoordinate(24, 3,
        "/lib/tests/support/pathfinding/24x3.c", "path");
    setCoordinate(24, 4,
        "/lib/tests/support/pathfinding/24x4.c", "room");
    setCoordinate(24, 5,
        "/lib/tests/support/pathfinding/24x5.c", "path");
    setCoordinate(24, 6,
        "/lib/tests/support/pathfinding/24x6.c", "path");
    setCoordinate(24, 7,
        "/lib/tests/support/pathfinding/24x7.c", "path");
    setCoordinate(24, 8,
        "/lib/tests/support/pathfinding/24x8.c", "path");
    setCoordinate(2, 0,
        "/lib/tests/support/pathfinding/2x0.c", "path");
    setCoordinate(2, 1,
        "/lib/tests/support/pathfinding/2x1.c", "path");
    setCoordinate(2, 2,
        "/lib/tests/support/pathfinding/2x2.c", "room");
    setCoordinate(2, 3,
        "/lib/tests/support/pathfinding/2x3.c", "path");
    setCoordinate(2, 5,
        "/lib/tests/support/pathfinding/2x5.c", "path");
    setCoordinate(2, 6,
        "/lib/tests/support/pathfinding/2x6.c", "room");
    setCoordinate(2, 7,
        "/lib/tests/support/pathfinding/2x7.c", "path");
    setCoordinate(2, 8,
        "/lib/tests/support/pathfinding/2x8.c", "path");
    setCoordinate(2, 9,
        "/lib/tests/support/pathfinding/2x9.c", "room");
    setCoordinate(3, 0,
        "/lib/tests/support/pathfinding/3x0.c", "path");
    setCoordinate(3, 1,
        "/lib/tests/support/pathfinding/3x1.c", "path");
    setCoordinate(3, 3,
        "/lib/tests/support/pathfinding/3x3.c", "path");
    setCoordinate(3, 4,
        "/lib/tests/support/pathfinding/3x4.c", "room");
    setCoordinate(3, 6,
        "/lib/tests/support/pathfinding/3x6.c", "room");
    setCoordinate(3, 7,
        "/lib/tests/support/pathfinding/3x7.c", "path");
    setCoordinate(3, 8,
        "/lib/tests/support/pathfinding/3x8.c", "path");
    setCoordinate(3, 9,
        "/lib/tests/support/pathfinding/3x9.c", "path");
    setCoordinate(4, 0,
        "/lib/tests/support/pathfinding/4x0.c", "room");
    setCoordinate(4, 1,
        "/lib/tests/support/pathfinding/4x1.c", "path");
    setCoordinate(4, 5,
        "/lib/tests/support/pathfinding/4x5.c", "room");
    setCoordinate(4, 6,
        "/lib/tests/support/pathfinding/4x6.c", "path");
    setCoordinate(4, 7,
        "/lib/tests/support/pathfinding/4x7.c", "path");
    setCoordinate(4, 8,
        "/lib/tests/support/pathfinding/4x8.c", "path");
    setCoordinate(5, 0,
        "/lib/tests/support/pathfinding/5x0.c", "path");
    setCoordinate(5, 1,
        "/lib/tests/support/pathfinding/5x1.c", "path");
    setCoordinate(5, 2,
        "/lib/tests/support/pathfinding/5x2.c", "room");
    setCoordinate(5, 5,
        "/lib/tests/support/pathfinding/5x5.c", "path");
    setCoordinate(5, 6,
        "/lib/tests/support/pathfinding/5x6.c", "path");
    setCoordinate(5, 8,
        "/lib/tests/support/pathfinding/5x8.c", "path");
    setCoordinate(5, 9,
        "/lib/tests/support/pathfinding/5x9.c", "path");
    setCoordinate(6, 0,
        "/lib/tests/support/pathfinding/6x0.c", "path");
    setCoordinate(6, 1,
        "/lib/tests/support/pathfinding/6x1.c", "path");
    setCoordinate(6, 5,
        "/lib/tests/support/pathfinding/6x5.c", "path");
    setCoordinate(6, 6,
        "/lib/tests/support/pathfinding/6x6.c", "room");
    setCoordinate(6, 7,
        "/lib/tests/support/pathfinding/6x7.c", "room");
    setCoordinate(6, 8,
        "/lib/tests/support/pathfinding/6x8.c", "path");
    setCoordinate(6, 9,
        "/lib/tests/support/pathfinding/6x9.c", "path");
    setCoordinate(7, 0,
        "/lib/tests/support/pathfinding/7x0.c", "room");
    setCoordinate(7, 5,
        "/lib/tests/support/pathfinding/7x5.c", "path");
    setCoordinate(7, 7,
        "/lib/tests/support/pathfinding/7x7.c", "room");
    setCoordinate(7, 9,
        "/lib/tests/support/pathfinding/7x9.c", "path");
    setCoordinate(8, 0,
        "/lib/tests/support/pathfinding/8x0.c", "path");
    setCoordinate(8, 5,
        "/lib/tests/support/pathfinding/8x5.c", "path");
    setCoordinate(8, 9,
        "/lib/tests/support/pathfinding/8x9.c", "path");
    setCoordinate(9, 0,
        "/lib/tests/support/pathfinding/9x0.c", "path");
    setCoordinate(9, 1,
        "/lib/tests/support/pathfinding/9x1.c", "room");
    setCoordinate(9, 4,
        "/lib/tests/support/pathfinding/9x4.c", "room");
    setCoordinate(9, 5,
        "/lib/tests/support/pathfinding/9x5.c", "path");
    setCoordinate(9, 6,
        "/lib/tests/support/pathfinding/9x6.c", "path");
    setCoordinate(9, 7,
        "/lib/tests/support/pathfinding/9x7.c", "path");
    setCoordinate(9, 8,
        "/lib/tests/support/pathfinding/9x8.c", "path");
    setCoordinate(9, 9,
        "/lib/tests/support/pathfinding/9x9.c", "path");
}
