//*****************************************************************************
// Copyright (c) 2021 - Allen Cummings, RealmsMUD, All rights reserved. See
//                      the accompanying LICENSE file for details.
//*****************************************************************************
inherit "/lib/environment/region.c";

/////////////////////////////////////////////////////////////////////////////
public void Setup()
{
    setRegionName("Western");
    setRegionType("forest");
    setDimensions(25, 10);
    // EntryCoordinate
    setSettlementChance(-1);

    setCoordinate(0, 0,
        "/areas/eledhel/west-rural-two/0x0.c", "path");
    setCoordinate(0, 1,
        "/areas/eledhel/west-rural-two/0x1.c", "path");
    setCoordinate(0, 2,
        "/areas/eledhel/west-rural-two/0x2.c", "path");
    setCoordinate(0, 3,
        "/areas/eledhel/west-rural-two/0x3.c", "path");
    setCoordinate(10, 0,
        "/areas/eledhel/west-rural-two/10x0.c", "room");
    setCoordinate(10, 1,
        "/areas/eledhel/west-rural-two/10x1.c", "room");
    setCoordinate(10, 2,
        "/areas/eledhel/west-rural-two/10x2.c", "path");
    setCoordinate(10, 3,
        "/areas/eledhel/west-rural-two/10x3.c", "room");
    setCoordinate(10, 4,
        "/areas/eledhel/west-rural-two/10x4.c", "room");
    setCoordinate(10, 5,
        "/areas/eledhel/west-rural-two/10x5.c", "room");
    setCoordinate(10, 8,
        "/areas/eledhel/west-rural-two/10x8.c", "path");
    setCoordinate(10, 9,
        "/areas/eledhel/west-rural-two/10x9.c", "path");
    setCoordinate(11, 0,
        "/areas/eledhel/west-rural-two/11x0.c", "path");
    setCoordinate(11, 4,
        "/areas/eledhel/west-rural-two/11x4.c", "path");
    setCoordinate(11, 6,
        "/areas/eledhel/west-rural-two/11x6.c", "path");
    setCoordinate(11, 7,
        "/areas/eledhel/west-rural-two/11x7.c", "path");
    setCoordinate(11, 8,
        "/areas/eledhel/west-rural-two/11x8.c", "path");
    setCoordinate(11, 9,
        "/areas/eledhel/west-rural-two/11x9.c", "room");
    setCoordinate(12, 0,
        "/areas/eledhel/west-rural-two/12x0.c", "path");
    setCoordinate(12, 4,
        "/areas/eledhel/west-rural-two/12x4.c", "path");
    setCoordinate(12, 5,
        "/areas/eledhel/west-rural-two/12x5.c", "path");
    setCoordinate(12, 6,
        "/areas/eledhel/west-rural-two/12x6.c", "path");
    setCoordinate(12, 7,
        "/areas/eledhel/west-rural-two/12x7.c", "path");
    setCoordinate(12, 8,
        "/areas/eledhel/west-rural-two/12x8.c", "path");
    setCoordinate(13, 0,
        "/areas/eledhel/west-rural-two/13x0.c", "path");
    setCoordinate(13, 5,
        "/areas/eledhel/west-rural-two/13x5.c", "path");
    setCoordinate(13, 6,
        "/areas/eledhel/west-rural-two/13x6.c", "path");
    setCoordinate(13, 7,
        "/areas/eledhel/west-rural-two/13x7.c", "path");
    setCoordinate(13, 8,
        "/areas/eledhel/west-rural-two/13x8.c", "room");
    setCoordinate(13, 9,
        "/areas/eledhel/west-rural-two/13x9.c", "path");
    setCoordinate(14, 0,
        "/areas/eledhel/west-rural-two/14x0.c", "path");
    setCoordinate(14, 5,
        "/areas/eledhel/west-rural-two/14x5.c", "path");
    setCoordinate(14, 9,
        "/areas/eledhel/west-rural-two/14x9.c", "entry");
    setCoordinate(15, 0,
        "/areas/eledhel/west-rural-two/15x0.c", "path");
    setCoordinate(15, 1,
        "/areas/eledhel/west-rural-two/15x1.c", "path");
    setCoordinate(15, 2,
        "/areas/eledhel/west-rural-two/15x2.c", "path");
    setCoordinate(15, 3,
        "/areas/eledhel/west-rural-two/15x3.c", "path");
    setCoordinate(15, 5,
        "/areas/eledhel/west-rural-two/15x5.c", "path");
    setCoordinate(15, 9,
        "/areas/eledhel/west-rural-two/15x9.c", "path");
    setCoordinate(16, 3,
        "/areas/eledhel/west-rural-two/16x3.c", "room");
    setCoordinate(16, 4,
        "/areas/eledhel/west-rural-two/16x4.c", "room");
    setCoordinate(16, 5,
        "/areas/eledhel/west-rural-two/16x5.c", "path");
    setCoordinate(16, 6,
        "/areas/eledhel/west-rural-two/16x6.c", "path");
    setCoordinate(16, 7,
        "/areas/eledhel/west-rural-two/16x7.c", "path");
    setCoordinate(16, 8,
        "/areas/eledhel/west-rural-two/16x8.c", "path");
    setCoordinate(16, 9,
        "/areas/eledhel/west-rural-two/16x9.c", "path");
    setCoordinate(17, 4,
        "/areas/eledhel/west-rural-two/17x4.c", "path");
    setCoordinate(17, 5,
        "/areas/eledhel/west-rural-two/17x5.c", "path");
    setCoordinate(17, 8,
        "/areas/eledhel/west-rural-two/17x8.c", "path");
    setCoordinate(18, 5,
        "/areas/eledhel/west-rural-two/18x5.c", "path");
    setCoordinate(18, 6,
        "/areas/eledhel/west-rural-two/18x6.c", "path");
    setCoordinate(18, 7,
        "/areas/eledhel/west-rural-two/18x7.c", "path");
    setCoordinate(18, 8,
        "/areas/eledhel/west-rural-two/18x8.c", "path");
    setCoordinate(18, 9,
        "/areas/eledhel/west-rural-two/18x9.c", "path");
    setCoordinate(19, 5,
        "/areas/eledhel/west-rural-two/19x5.c", "path");
    setCoordinate(19, 6,
        "/areas/eledhel/west-rural-two/19x6.c", "room");
    setCoordinate(19, 9,
        "/areas/eledhel/west-rural-two/19x9.c", "path");
    setCoordinate(1, 0,
        "/areas/eledhel/west-rural-two/1x0.c", "exit");
    setCoordinate(1, 2,
        "/areas/eledhel/west-rural-two/1x2.c", "room");
    setCoordinate(1, 3,
        "/areas/eledhel/west-rural-two/1x3.c", "path");
    setCoordinate(1, 4,
        "/areas/eledhel/west-rural-two/1x4.c", "path");
    setCoordinate(1, 5,
        "/areas/eledhel/west-rural-two/1x5.c", "path");
    setCoordinate(1, 6,
        "/areas/eledhel/west-rural-two/1x6.c", "room");
    setCoordinate(20, 3,
        "/areas/eledhel/west-rural-two/20x3.c", "room");
    setCoordinate(20, 4,
        "/areas/eledhel/west-rural-two/20x4.c", "room");
    setCoordinate(20, 5,
        "/areas/eledhel/west-rural-two/20x5.c", "room");
    setCoordinate(20, 6,
        "/areas/eledhel/west-rural-two/20x6.c", "path");
    setCoordinate(20, 9,
        "/areas/eledhel/west-rural-two/20x9.c", "path");
    setCoordinate(21, 1,
        "/areas/eledhel/west-rural-two/21x1.c", "path");
    setCoordinate(21, 2,
        "/areas/eledhel/west-rural-two/21x2.c", "path");
    setCoordinate(21, 3,
        "/areas/eledhel/west-rural-two/21x3.c", "path");
    setCoordinate(21, 9,
        "/areas/eledhel/west-rural-two/21x9.c", "path");
    setCoordinate(22, 1,
        "/areas/eledhel/west-rural-two/22x1.c", "room");
    setCoordinate(22, 3,
        "/areas/eledhel/west-rural-two/22x3.c", "room");
    setCoordinate(22, 6,
        "/areas/eledhel/west-rural-two/22x6.c", "path");
    setCoordinate(22, 7,
        "/areas/eledhel/west-rural-two/22x7.c", "path");
    setCoordinate(22, 8,
        "/areas/eledhel/west-rural-two/22x8.c", "path");
    setCoordinate(22, 9,
        "/areas/eledhel/west-rural-two/22x9.c", "room");
    setCoordinate(23, 0,
        "/areas/eledhel/west-rural-two/23x0.c", "path");
    setCoordinate(23, 1,
        "/areas/eledhel/west-rural-two/23x1.c", "path");
    setCoordinate(23, 2,
        "/areas/eledhel/west-rural-two/23x2.c", "path");
    setCoordinate(23, 5,
        "/areas/eledhel/west-rural-two/23x5.c", "path");
    setCoordinate(23, 6,
        "/areas/eledhel/west-rural-two/23x6.c", "path");
    setCoordinate(24, 0,
        "/areas/eledhel/west-rural-two/24x0.c", "path");
    setCoordinate(24, 1,
        "/areas/eledhel/west-rural-two/24x1.c", "room");
    setCoordinate(24, 2,
        "/areas/eledhel/west-rural-two/24x2.c", "path");
    setCoordinate(24, 3,
        "/areas/eledhel/west-rural-two/24x3.c", "path");
    setCoordinate(24, 4,
        "/areas/eledhel/west-rural-two/24x4.c", "path");
    setCoordinate(24, 5,
        "/areas/eledhel/west-rural-two/24x5.c", "room");
    setCoordinate(2, 0,
        "/areas/eledhel/west-rural-two/2x0.c", "path");
    setCoordinate(2, 1,
        "/areas/eledhel/west-rural-two/2x1.c", "path");
    setCoordinate(2, 2,
        "/areas/eledhel/west-rural-two/2x2.c", "path");
    setCoordinate(3, 0,
        "/areas/eledhel/west-rural-two/3x0.c", "path");
    setCoordinate(3, 1,
        "/areas/eledhel/west-rural-two/3x1.c", "path");
    setCoordinate(3, 5,
        "/areas/eledhel/west-rural-two/3x5.c", "path");
    setCoordinate(3, 6,
        "/areas/eledhel/west-rural-two/3x6.c", "room");
    setCoordinate(3, 7,
        "/areas/eledhel/west-rural-two/3x7.c", "path");
    setCoordinate(3, 8,
        "/areas/eledhel/west-rural-two/3x8.c", "room");
    setCoordinate(4, 1,
        "/areas/eledhel/west-rural-two/4x1.c", "path");
    setCoordinate(4, 5,
        "/areas/eledhel/west-rural-two/4x5.c", "path");
    setCoordinate(4, 6,
        "/areas/eledhel/west-rural-two/4x6.c", "path");
    setCoordinate(4, 7,
        "/areas/eledhel/west-rural-two/4x7.c", "path");
    setCoordinate(5, 1,
        "/areas/eledhel/west-rural-two/5x1.c", "path");
    setCoordinate(5, 2,
        "/areas/eledhel/west-rural-two/5x2.c", "path");
    setCoordinate(5, 5,
        "/areas/eledhel/west-rural-two/5x5.c", "path");
    setCoordinate(5, 6,
        "/areas/eledhel/west-rural-two/5x6.c", "path");
    setCoordinate(5, 7,
        "/areas/eledhel/west-rural-two/5x7.c", "path");
    setCoordinate(5, 9,
        "/areas/eledhel/west-rural-two/5x9.c", "room");
    setCoordinate(6, 2,
        "/areas/eledhel/west-rural-two/6x2.c", "path");
    setCoordinate(6, 3,
        "/areas/eledhel/west-rural-two/6x3.c", "path");
    setCoordinate(6, 5,
        "/areas/eledhel/west-rural-two/6x5.c", "room");
    setCoordinate(6, 6,
        "/areas/eledhel/west-rural-two/6x6.c", "path");
    setCoordinate(6, 7,
        "/areas/eledhel/west-rural-two/6x7.c", "path");
    setCoordinate(6, 9,
        "/areas/eledhel/west-rural-two/6x9.c", "path");
    setCoordinate(7, 2,
        "/areas/eledhel/west-rural-two/7x2.c", "room");
    setCoordinate(7, 3,
        "/areas/eledhel/west-rural-two/7x3.c", "path");
    setCoordinate(7, 4,
        "/areas/eledhel/west-rural-two/7x4.c", "path");
    setCoordinate(7, 5,
        "/areas/eledhel/west-rural-two/7x5.c", "path");
    setCoordinate(7, 6,
        "/areas/eledhel/west-rural-two/7x6.c", "path");
    setCoordinate(7, 7,
        "/areas/eledhel/west-rural-two/7x7.c", "room");
    setCoordinate(7, 9,
        "/areas/eledhel/west-rural-two/7x9.c", "path");
    setCoordinate(8, 2,
        "/areas/eledhel/west-rural-two/8x2.c", "path");
    setCoordinate(8, 5,
        "/areas/eledhel/west-rural-two/8x5.c", "path");
    setCoordinate(8, 7,
        "/areas/eledhel/west-rural-two/8x7.c", "path");
    setCoordinate(8, 8,
        "/areas/eledhel/west-rural-two/8x8.c", "path");
    setCoordinate(8, 9,
        "/areas/eledhel/west-rural-two/8x9.c", "path");
    setCoordinate(9, 2,
        "/areas/eledhel/west-rural-two/9x2.c", "path");
    setCoordinate(9, 5,
        "/areas/eledhel/west-rural-two/9x5.c", "path");
    setCoordinate(9, 6,
        "/areas/eledhel/west-rural-two/9x6.c", "room");
    setCoordinate(9, 8,
        "/areas/eledhel/west-rural-two/9x8.c", "room");
    setCoordinate(9, 9,
        "/areas/eledhel/west-rural-two/9x9.c", "path");

    // MapIcons
}
