//*****************************************************************************
// Copyright (c) 2025 - Allen Cummings, RealmsMUD, All rights reserved. See
//                      the accompanying LICENSE file for details.
//*****************************************************************************
#ifndef instruments_h
#define instruments_h

protected mapping instrumentBlueprints = ([
    "bagpipes": ([
        "type": "pipes",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftPipes.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "sewing": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "leather": 2,
            "textile": 2
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "yew",
        "default value": 200,
        "default description": "This wind instrument has multiple reed pipes attached to an air bag that produces sound when squeezed.",
        "base experience": 10,
    ]),
    "uilleann pipes": ([
        "type": "pipes",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 15,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftPipes.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 2]),
            "sewing": (["type":"skill", "value": 2]),
            "metal crafting": (["type":"skill", "value": 3]),
        ]), 
        "crafting materials": ([
            "metal": 2,
            "wood": 2,
            "leather": 2,
            "textile": 2
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "yew",
        "default value": 200,
        "default description": "This sophisticated bellows-blown bagpipe features drones, regulators, and a chanter for melodic control.",
        "base experience": 15,
    ]),
    "warpipes": ([
        "type": "pipes",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftPipes.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "sewing": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "leather": 2,
            "textile": 2
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "yew",
        "default value": 200,
        "default description": "This loud bagpipe with a powerful drone was designed to be heard across battlefields and strike fear into enemies.",
        "base experience": 10,
    ]),
    "fierabras": ([
        "type": "pipes",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftPipes.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "sewing": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "leather": 2,
            "textile": 2
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "yew",
        "default value": 200,
        "default description": "This bagpipe variant features decorative tassels and produces a distinctive buzzing tone through its multiple reed pipes.",
        "base experience": 10,
    ]),
    "zampogna": ([
        "type": "pipes",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftPipes.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "sewing": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "metal": 1,
            "wood": 2,
            "leather": 2,
            "textile": 2
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "yew",
        "default value": 200,
        "default description": "This traditional bagpipe has two parallel chanters with unequal lengths and produces melodic folk tunes.",
        "base experience": 10,
    ]),
    "surdullina": ([
        "type": "pipes",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftPipes.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "sewing": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "metal": 1,
            "wood": 2,
            "leather": 2,
            "textile": 2
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "yew",
        "default value": 200,
        "default description": "This small bagpipe has a distinctive nasal tone and uses a simple leather bag with two or three drone pipes.",
        "base experience": 10,
    ]),
    "hummelchen": ([
        "type": "pipes",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftPipes.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "sewing": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "leather": 2,
            "textile": 2
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "yew",
        "default value": 200,
        "default description": "This small, quieter bellows-blown bagpipe is designed for indoor performances and chamber music.",
        "base experience": 10,
    ]),
    "piffero": ([
        "type": "woodwind",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftOboe.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 6]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 3]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "metal": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This double-reed folk woodwind instrument has a conical bore and bright, penetrating sound.",
        "base experience": 10,
    ]),
    "ciaramella": ([
        "type": "woodwind",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftOboe.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "metal": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This traditional wooden shawm has a flared bell and produces a loud, reedy tone ideal for outdoor celebrations.",
        "base experience": 10,
    ]),
    "blaterpfeife": ([
        "type": "pipes",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftPipes.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "sewing": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "leather": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This bladder pipe has a wooden pipe attached to an inflated animal bladder that produces a nasal drone.",
        "base experience": 10,
    ]),
    "cornamuse": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 5,
            "metal": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 4,
        "default material": "yew",
        "default value": 100,
        "default description": "This capped double-reed instrument has a cylindrical bore and a soft, mellow tone suitable for ensembles.",
        "base experience": 10,
    ]),
    "crumhorn": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "metal": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This J-shaped double-reed instrument has a capped reed and produces a distinctive buzzing tone.",
        "base experience": 10,
    ]),
    "kortholt": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 8,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 7]),
            "wood crafting": (["type":"skill", "value": 1])
        ]), 
        "crafting materials": ([
            "wood": 3,
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This short, cylindrical double-reed instrument has a folded bore and produces a soft, muted tone.",
        "base experience": 10,
    ]),
    "recorder": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 2])
        ]), 
        "crafting materials": ([
            "wood": 3,
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This end-blown fipple flute has a tapered bore and produces a clear, sweet tone across its range.",
        "base experience": 10,
    ]),
    "hirtenschalmei": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 2])
        ]), 
        "crafting materials": ([
            "wood": 4,
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This shepherd's shawm has a capped double-reed and produces a bright, rustic tone ideal for folk music.",
        "base experience": 10,
    ]),
    "shawm": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "metal": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This double-reed instrument has a conical bore and flaring bell that produces a powerful, penetrating sound.",
        "base experience": 10,
    ]),
    "dulcian": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "sewing": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "metal": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This early bassoon has a U-shaped bore and double reed, producing a warm, resonant bass tone.",
        "base experience": 10,
    ]),
    "shagbut": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "metal": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This early slide trumpet has a telescoping mechanism and produces a mellow, noble brass tone.",
        "base experience": 10,
    ]),
    "cornett": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "sewing": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "metal": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This curved wooden instrument has a cup mouthpiece and finger holes, with a sound between brass and woodwind.",
        "base experience": 10,
    ]),
    "horn": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "sewing": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "metal": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This simple brass instrument has a conical bore and cup mouthpiece, producing a clear, projecting tone.",
        "base experience": 10,
    ]),
    "oboe": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "sewing": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "metal": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This double-reed woodwind has a conical bore and produces a clear, somewhat nasal tone quality.",
        "base experience": 10,
    ]),
    "lyserden": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "sewing": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "metal": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This reed pipe has a narrow cylindrical bore and produces a clear, sweet tone suitable for folk melodies.",
        "base experience": 10,
    ]),
    "gemshorn": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "exotic": 3,
            "metal": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This flute-like instrument is made from an animal horn with finger holes and produces a soft, haunting tone.",
        "base experience": 10,
    ]),
    "flute": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 27,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftWindcap.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 3]),
            "metal crafting": (["type":"skill", "value": 3]),
            "engineering": (["type":"skill", "value": 7]),
        ]), 
        "crafting materials": ([
            "exotic": 1,
            "metal": 4,
            "wood": 1,
            "leather": 1
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "brass",
        "default value": 200,
        "default description": "This transverse wind instrument has a row of tone holes and produces a bright, agile sound.",
        "base experience": 10,
    ]),
    "ocarina": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/woodwind/craftOcarina.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 8]),
            "pottery": (["type":"skill", "value": 1]),
            "sculpture": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "clay": 3
        ]),
        "skill to use": "instrument: woodwind",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "yew",
        "default value": 100,
        "default description": "This hollow, vessel flute is usually made of ceramic and produces a warm, whistling tone.",
        "base experience": 10,
    ]),
    "trumpet": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 27,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/brass/craftTrumpet.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 3]),
            "metal crafting": (["type":"skill", "value": 3]),
            "engineering": (["type":"skill", "value": 7]),
        ]), 
        "crafting materials": ([
            "exotic": 1,
            "metal": 4,
            "wood": 1,
            "leather": 1
        ]),
        "skill to use": "instrument: brass",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "brass",
        "default value": 300,
        "default description": "This brass instrument has a cup-shaped mouthpiece and flared bell, producing a brilliant, powerful tone.",
        "base experience": 10,
    ]),
    "bugle": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/brass/craftTrumpet.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 10]),
            "metal crafting": (["type":"skill", "value": 5]),
            "engineering": (["type":"skill", "value": 5]),
        ]), 
        "crafting materials": ([
            "exotic": 1,
            "metal": 5,
            "leather": 1
        ]),
        "skill to use": "instrument: brass",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "brass",
        "default value": 250,
        "default description": "This coiled brass horn has no valves and relies on the player's embouchure to produce different notes.",
        "base experience": 10,
    ]),
    "sackbut": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/brass/craftTrumpet.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 10]),
            "wood crafting": (["type":"skill", "value": 3]),
            "metal crafting": (["type":"skill", "value": 3]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "metal": 4,
            "wood": 1,
            "leather": 1
        ]),
        "skill to use": "instrument: brass",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "brass",
        "default value": 200,
        "default description": "This early trombone has a telescoping slide and produces a mellow, dignified tone.",
        "base experience": 10,
    ]),
    "trombone": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 35,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/brass/craftTrumpet.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 22]),
            "wood crafting": (["type":"skill", "value": 3]),
            "metal crafting": (["type":"skill", "value": 3]),
            "engineering": (["type":"skill", "value": 7]),
        ]), 
        "crafting materials": ([
            "exotic": 1,
            "metal": 4,
            "wood": 1,
            "leather": 1
        ]),
        "skill to use": "instrument: brass",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "brass",
        "default value": 300,
        "default description": "This brass instrument has a telescoping slide and produces a rich, powerful tone across a wide range.",
        "base experience": 10,
    ]),
    "tuba": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 35,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/brass/craftTrumpet.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 22]),
            "wood crafting": (["type":"skill", "value": 3]),
            "metal crafting": (["type":"skill", "value": 3]),
            "engineering": (["type":"skill", "value": 7]),
        ]), 
        "crafting materials": ([
            "exotic": 1,
            "metal": 4,
            "wood": 1,
            "leather": 1
        ]),
        "skill to use": "instrument: brass",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "brass",
        "default value": 300,
        "default description": "This large brass instrument has a conical bore, valves, and produces a deep, rich bass tone.",
        "base experience": 10,
    ]),
    "french horn": ([
        "type": "windcap",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 40,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/brass/craftTrumpet.c":(["type":"research"]),
            "aerophone crafting": (["type":"skill", "value": 24]),
            "wood crafting": (["type":"skill", "value": 3]),
            "metal crafting": (["type":"skill", "value": 3]),
            "engineering": (["type":"skill", "value": 10]),
        ]), 
        "crafting materials": ([
            "exotic": 1,
            "metal": 4,
            "wood": 1,
            "leather": 1
        ]),
        "skill to use": "instrument: brass",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "brass",
        "default value": 300,
        "default description": "This coiled brass horn has valves and produces a warm, mellow tone prized for its expressiveness.",
        "base experience": 10,
    ]),
    "dulcimer": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftDulcimer.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "leather crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "leather": 1,
            "textile": 1
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "ash",
        "default value": 100,
        "default description": "This trapezoid-shaped string instrument is played by striking the strings with small hammers.",
        "base experience": 10,
    ]),
    "rebec": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftDulcimer.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "leather crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "leather": 1,
            "textile": 2
        ]),
        "skill to use": "instrument: bowed",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "ash",
        "default value": 150,
        "default description": "This bowed string instrument has a pear-shaped body and produces a bright, nasal tone.",
        "base experience": 10,
    ]),
    "harp": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftDulcimer.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "leather crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "metal": 3,
            "wood": 3,
            "leather": 1,
            "textile": 2
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "alder",
        "default value": 200,
        "default description": "This triangular string instrument has strings of varying length played by plucking with the fingers.",
        "base experience": 10,
    ]),
    "zither": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 15,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftDulcimer.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 2]),
            "leather crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "metal": 2,
            "wood": 5,
            "leather": 1,
            "textile": 2
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "alder",
        "default value": 150,
        "default description": "This flat string instrument has many strings stretched over a resonating box and is played by plucking.",
        "base experience": 10,
    ]),
    "gamba": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftViol.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "leather crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "leather": 2,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: bowed",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "ash",
        "default value": 100,
        "default description": "This six-stringed bowed instrument is held between the legs and produces a warm, resonant tone.",
        "base experience": 10,
    ]),
    "bass viol": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftViol.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "leather crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "leather": 2,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: bowed",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "ash",
        "default value": 100,
        "default description": "This large bowed string instrument produces deep bass tones and stands on the floor when played.",
        "base experience": 10,
    ]),
    "violin": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftViol.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "leather crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "leather": 2,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: bowed",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "ash",
        "default value": 100,
        "default description": "This four-string bowed instrument is held under the chin and produces a bright, singing tone.",
        "base experience": 10,
    ]),
    "viol": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftViol.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "leather crafting": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "leather": 2,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: bowed",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "ash",
        "default value": 100,
        "default description": "This fretted bowed string instrument has a flat back and produces a soft, sweet tone.",
        "base experience": 10,
    ]),
    "hurdy-gurdy": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftMechanical.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 1]),
            "physics": (["type":"skill", "value": 5]),
            "engineering": (["type":"skill", "value": 5]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "leather": 2,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: bowed",
        "default weight": 1,
        "default encumberance": 2,
        "default material": "ash",
        "default value": 100,
        "default description": "This mechanical string instrument produces sound when a crank turns a wheel against strings.",
        "base experience": 10,
    ]),
    "lute": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 15,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftLute.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 5,
            "textile": 2,
            "metal": 1
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 250,
        "default description": "This plucked string instrument has a pear-shaped body, bent neck, and produces a warm, delicate tone.",
        "base experience": 10,
    ]),
    "chittarone": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 15,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftLute.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 5,
            "textile": 2,
            "metal": 1
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 300,
        "default description": "This bass lute has an extended neck almost as tall as a person and produces resonant bass notes.",
        "base experience": 10,
    ]),
    "archlute": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftLute.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 350,
        "default description": "This lute variant has an elongated neck with a second pegbox for bass strings that run alongside the fingerboard.",
        "base experience": 10,
    ]),
    "gittern": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftGuitar.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 300,
        "default description": "This small, round-backed string instrument is an ancestor of the guitar with a bright, lively tone.",
        "base experience": 10,
    ]),
    "vihuella": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 22,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftGuitar.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 3
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 350,
        "default description": "This guitar-like instrument has six double courses of strings and a figure-eight shaped body.",
        "base experience": 10,
    ]),
    "baroque guitar": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 22,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftGuitar.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 3
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 350,
        "default description": "This five-course guitar has a body smaller than modern guitars and produces a delicate, bright tone.",
        "base experience": 10,
    ]),
    "citole": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 16,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftGuitar.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 5,
            "textile": 2,
            "metal": 3
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 400,
        "default description": "This carved wooden string instrument has an asymmetrical shape and produces a bright, clear tone.",
        "base experience": 10,
    ]),
    "guitar": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 25,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftGuitar.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 15]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 3
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 400,
        "default description": "This six-stringed instrument has a figure-eight wooden body and produces a versatile, resonant tone.",
        "base experience": 10,
    ]),
    "bass guitar": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 25,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftGuitar.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 15]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 3
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 400,
        "default description": "This larger guitar has four thick strings and produces deep bass tones with a rich resonance.",
        "base experience": 10,
    ]),
    "12-string guitar": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 25,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftGuitar.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 15]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 3
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 400,
        "default description": "This guitar has six courses of doubled strings that create a rich, chorus-like effect when strummed.",
        "base experience": 10,
    ]),
    "resonating guitar": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 25,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftGuitar.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 15]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 1,
            "textile": 2,
            "metal": 8
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "iron",
        "default value": 450,
        "default description": "This guitar has a metal resonator built into its body that amplifies the sound with distinctive clarity.",
        "base experience": 10,
    ]),
    "banjo": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 25,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftGuitar.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 15]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 3,
            "metal": 3
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "iron",
        "default value": 400,
        "default description": "This instrument has strings stretched over a circular frame with a drum-like membrane that produces a bright, twangy sound.",
        "base experience": 10,
    ]),
    "mandolin": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 18,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftMandolin.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 10]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 200,
        "default description": "This small, pear-shaped string instrument has four pairs of strings and produces a bright, trembling tone.",
        "base experience": 10,
    ]),
    "cittern": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftMandolin.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 250,
        "default description": "This flat-backed string instrument has metal strings and produces a bright, ringing tone.",
        "base experience": 10,
    ]),
    "bandurria": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftMandolin.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 250,
        "default description": "This pear-shaped string instrument has six double courses of strings and produces a bright, percussive tone.",
        "base experience": 10,
    ]),
    "mandore": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftMandolin.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 250,
        "default description": "This small lute-like instrument has four to six courses of strings and produces a delicate, sweet tone.",
        "base experience": 10,
    ]),
    "gallichon": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftMandolin.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 250,
        "default description": "This bass lute has a long neck, six single strings, and produces deep, resonant bass tones.",
        "base experience": 10,
    ]),
    "12-string mandolin": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 25,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftMandolin.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 15]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 2]),
            "engineering": (["type":"skill", "value": 3]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 3
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 450,
        "default description": "This mandolin has six courses of doubled strings that create a rich, complex sound with enhanced resonance.",
        "base experience": 10,
    ]),
    "mandocello": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftMandolin.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 250,
        "default description": "This large bass member of the mandolin family has four paired strings and produces deep, resonant tones.",
        "base experience": 10,
    ]),
    "bozuk": ([
        "type": "string instrument",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/strings/craftMandolin.c":(["type":"research"]),
            "luthiery": (["type":"skill", "value": 12]),
            "wood crafting": (["type":"skill", "value": 5]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 2]),
        ]), 
        "crafting materials": ([
            "wood": 6,
            "textile": 2,
            "metal": 2
        ]),
        "skill to use": "instrument: plucked",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 250,
        "default description": "This long-necked string instrument has movable frets and produces melodic tones popular in folk music.",
        "base experience": 10,
    ]),
    "adufe": ([
        "type": "percussion",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 6,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/percussion/craftDrum.c":(["type":"research"]),
            "drum crafting": (["type":"skill", "value": 3]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "leather": 2,
            "metal": 1
        ]),
        "skill to use": "instrument: percussion",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 100,
        "default description": "This square frame drum has small objects inside that rattle when the drum is shaken or struck.",
        "base experience": 10,
    ]),
    "bodhran": ([
        "type": "percussion",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 6,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/percussion/craftDrum.c":(["type":"research"]),
            "drum crafting": (["type":"skill", "value": 3]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "leather": 2,
            "metal": 1
        ]),
        "skill to use": "instrument: percussion",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 100,
        "default description": "This frame drum with a goatskin head is played with a double-ended wooden stick called a tipper.",
        "base experience": 10,
    ]),
    "tabor": ([
        "type": "percussion",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 10,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/percussion/craftDrum.c":(["type":"research"]),
            "drum crafting": (["type":"skill", "value": 7]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 1]),
            "engineering": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "leather": 3,
            "metal": 1
        ]),
        "skill to use": "instrument: percussion",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 100,
        "default description": "This small cylindrical drum hangs from the player's wrist and is struck with a single stick.",
        "base experience": 10,
    ]),
    "timbrel": ([
        "type": "percussion",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 13,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/percussion/craftDrum.c":(["type":"research"]),
            "drum crafting": (["type":"skill", "value": 8]),
            "wood crafting": (["type":"skill", "value": 1]),
            "metal crafting": (["type":"skill", "value": 3]),
            "engineering": (["type":"skill", "value": 1]),
        ]), 
        "crafting materials": ([
            "wood": 3,
            "leather": 2,
            "metal": 3
        ]),
        "skill to use": "instrument: percussion",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 100,
        "default description": "This tambourine-like instrument has jingles mounted in the frame and produces a bright, rhythmic sound.",
        "base experience": 10,
    ]),
    "cymbals": ([
        "type": "percussion",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 8,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/percussion/craftDrum.c":(["type":"research"]),
            "drum crafting": (["type":"skill", "value": 4]),
            "metal crafting": (["type":"skill", "value": 4]),
        ]), 
        "crafting materials": ([
            "metal": 4
        ]),
        "skill to use": "instrument: percussion",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 100,
        "default description": "These paired metal plates produce a bright, ringing clash when struck together.",
        "base experience": 10,
    ]),
    "snare drum": ([
        "type": "percussion",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/percussion/craftDrum.c":(["type":"research"]),
            "drum crafting": (["type":"skill", "value": 10]),
            "wood crafting": (["type":"skill", "value": 3]),
            "metal crafting": (["type":"skill", "value": 3]),
            "engineering": (["type":"skill", "value": 4]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "leather": 4,
            "metal": 3
        ]),
        "skill to use": "instrument: percussion",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 300,
        "default description": "This double-headed drum has snares stretched across the bottom head that rattle when the top is struck.",
        "base experience": 10,
    ]),
    "bass drum": ([
        "type": "percussion",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/percussion/craftDrum.c":(["type":"research"]),
            "drum crafting": (["type":"skill", "value": 10]),
            "wood crafting": (["type":"skill", "value": 3]),
            "metal crafting": (["type":"skill", "value": 3]),
            "engineering": (["type":"skill", "value": 4]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "leather": 4,
            "metal": 4
        ]),
        "skill to use": "instrument: percussion",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 350,
        "default description": "This large cylindrical drum produces deep, powerful tones when struck with a padded mallet.",
        "base experience": 10,
    ]),
    "nakers": ([
        "type": "percussion",
        "default location": TwohandedWeapon,
        "damage type": "musical",
        "skill to craft": 20,
        "crafting prerequisites": ([
            "/lib/instances/research/crafting/instruments/percussion/craftDrum.c":(["type":"research"]),
            "drum crafting": (["type":"skill", "value": 10]),
            "wood crafting": (["type":"skill", "value": 3]),
            "metal crafting": (["type":"skill", "value": 3]),
            "engineering": (["type":"skill", "value": 4]),
        ]), 
        "crafting materials": ([
            "wood": 4,
            "leather": 4,
            "metal": 4
        ]),
        "skill to use": "instrument: percussion",
        "default weight": 2,
        "default encumberance": 5,
        "default material": "ash",
        "default value": 350,
        "default description": "These small kettle drums are played in pairs and produce sharp, crisp tones for military and ceremonial use.",
        "base experience": 10,
    ]),
]);

#endif
