//*****************************************************************************
// Copyright (c) 2020 - Allen Cummings, RealmsMUD, All rights reserved. See
//                      the accompanying LICENSE file for details.
//*****************************************************************************
inherit "/lib/environment/region.c";

/////////////////////////////////////////////////////////////////////////////
public void Setup()
{
    setRegionName("Tol-Dhurath Forest 3");
    setRegionType("forest");
    setDimensions(25, 10);
    // EntryCoordinate

    setCoordinate(0, 0,
        "/areas/tol-dhurath/forest-3/0x0.c", "room");
    setCoordinate(0, 1,
        "/areas/tol-dhurath/forest-3/0x1.c", "path");
    setCoordinate(0, 6,
        "/areas/tol-dhurath/forest-3/0x6.c", "path");
    setCoordinate(0, 7,
        "/areas/tol-dhurath/forest-3/0x7.c", "room");
    setCoordinate(0, 8,
        "/areas/tol-dhurath/forest-3/0x8.c", "exit");
    setCoordinate(10, 0,
        "/areas/tol-dhurath/forest-3/10x0.c", "path");
    setCoordinate(10, 1,
        "/areas/tol-dhurath/forest-3/10x1.c", "path");
    setCoordinate(10, 2,
        "/areas/tol-dhurath/forest-3/10x2.c", "path");
    setCoordinate(10, 3,
        "/areas/tol-dhurath/forest-3/10x3.c", "path");
    setCoordinate(10, 4,
        "/areas/tol-dhurath/forest-3/10x4.c", "path");
    setCoordinate(10, 5,
        "/areas/tol-dhurath/forest-3/10x5.c", "path");
    setCoordinate(10, 6,
        "/areas/tol-dhurath/forest-3/10x6.c", "path");
    setCoordinate(10, 7,
        "/areas/tol-dhurath/forest-3/10x7.c", "path");
    setCoordinate(10, 8,
        "/areas/tol-dhurath/forest-3/10x8.c", "path");
    setCoordinate(10, 9,
        "/areas/tol-dhurath/forest-3/10x9.c", "path");
    setCoordinate(11, 0,
        "/areas/tol-dhurath/forest-3/11x0.c", "path");
    setCoordinate(11, 1,
        "/areas/tol-dhurath/forest-3/11x1.c", "room");
    setCoordinate(11, 4,
        "/areas/tol-dhurath/forest-3/11x4.c", "room");
    setCoordinate(11, 8,
        "/areas/tol-dhurath/forest-3/11x8.c", "room");
    setCoordinate(11, 9,
        "/areas/tol-dhurath/forest-3/11x9.c", "path");
    setCoordinate(12, 0,
        "/areas/tol-dhurath/forest-3/12x0.c", "path");
    setCoordinate(12, 1,
        "/areas/tol-dhurath/forest-3/12x1.c", "path");
    setCoordinate(12, 2,
        "/areas/tol-dhurath/forest-3/12x2.c", "path");
    setCoordinate(12, 4,
        "/areas/tol-dhurath/forest-3/12x4.c", "path");
    setCoordinate(12, 5,
        "/areas/tol-dhurath/forest-3/12x5.c", "path");
    setCoordinate(12, 9,
        "/areas/tol-dhurath/forest-3/12x9.c", "path");
    setCoordinate(13, 2,
        "/areas/tol-dhurath/forest-3/13x2.c", "room");
    setCoordinate(13, 3,
        "/areas/tol-dhurath/forest-3/13x3.c", "path");
    setCoordinate(13, 4,
        "/areas/tol-dhurath/forest-3/13x4.c", "path");
    setCoordinate(13, 5,
        "/areas/tol-dhurath/forest-3/13x5.c", "path");
    setCoordinate(13, 9,
        "/areas/tol-dhurath/forest-3/13x9.c", "path");
    setCoordinate(14, 1,
        "/areas/tol-dhurath/forest-3/14x1.c", "path");
    setCoordinate(14, 2,
        "/areas/tol-dhurath/forest-3/14x2.c", "path");
    setCoordinate(14, 3,
        "/areas/tol-dhurath/forest-3/14x3.c", "path");
    setCoordinate(14, 4,
        "/areas/tol-dhurath/forest-3/14x4.c", "room");
    setCoordinate(14, 5,
        "/areas/tol-dhurath/forest-3/14x5.c", "room");
    setCoordinate(14, 9,
        "/areas/tol-dhurath/forest-3/14x9.c", "path");
    setCoordinate(15, 1,
        "/areas/tol-dhurath/forest-3/15x1.c", "path");
    setCoordinate(15, 3,
        "/areas/tol-dhurath/forest-3/15x3.c", "room");
    setCoordinate(15, 9,
        "/areas/tol-dhurath/forest-3/15x9.c", "path");
    setCoordinate(16, 0,
        "/areas/tol-dhurath/forest-3/16x0.c", "room");
    setCoordinate(16, 1,
        "/areas/tol-dhurath/forest-3/16x1.c", "room");
    setCoordinate(16, 2,
        "/areas/tol-dhurath/forest-3/16x2.c", "room");
    setCoordinate(16, 3,
        "/areas/tol-dhurath/forest-3/16x3.c", "path");
    setCoordinate(16, 8,
        "/areas/tol-dhurath/forest-3/16x8.c", "room");
    setCoordinate(16, 9,
        "/areas/tol-dhurath/forest-3/16x9.c", "path");
    setCoordinate(17, 3,
        "/areas/tol-dhurath/forest-3/17x3.c", "path");
    setCoordinate(17, 4,
        "/areas/tol-dhurath/forest-3/17x4.c", "path");
    setCoordinate(17, 5,
        "/areas/tol-dhurath/forest-3/17x5.c", "room");
    setCoordinate(17, 6,
        "/areas/tol-dhurath/forest-3/17x6.c", "path");
    setCoordinate(18, 3,
        "/areas/tol-dhurath/forest-3/18x3.c", "path");
    setCoordinate(18, 4,
        "/areas/tol-dhurath/forest-3/18x4.c", "path");
    setCoordinate(18, 5,
        "/areas/tol-dhurath/forest-3/18x5.c", "path");
    setCoordinate(18, 6,
        "/areas/tol-dhurath/forest-3/18x6.c", "path");
    setCoordinate(18, 7,
        "/areas/tol-dhurath/forest-3/18x7.c", "room");
    setCoordinate(19, 1,
        "/areas/tol-dhurath/forest-3/19x1.c", "room");
    setCoordinate(19, 2,
        "/areas/tol-dhurath/forest-3/19x2.c", "path");
    setCoordinate(19, 4,
        "/areas/tol-dhurath/forest-3/19x4.c", "room");
    setCoordinate(19, 5,
        "/areas/tol-dhurath/forest-3/19x5.c", "room");
    setCoordinate(19, 8,
        "/areas/tol-dhurath/forest-3/19x8.c", "room");
    setCoordinate(1, 0,
        "/areas/tol-dhurath/forest-3/1x0.c", "path");
    setCoordinate(1, 1,
        "/areas/tol-dhurath/forest-3/1x1.c", "path");
    setCoordinate(1, 6,
        "/areas/tol-dhurath/forest-3/1x6.c", "room");
    setCoordinate(1, 7,
        "/areas/tol-dhurath/forest-3/1x7.c", "path");
    setCoordinate(1, 8,
        "/areas/tol-dhurath/forest-3/1x8.c", "path");
    setCoordinate(20, 2,
        "/areas/tol-dhurath/forest-3/20x2.c", "room");
    setCoordinate(20, 3,
        "/areas/tol-dhurath/forest-3/20x3.c", "path");
    setCoordinate(20, 4,
        "/areas/tol-dhurath/forest-3/20x4.c", "path");
    setCoordinate(20, 5,
        "/areas/tol-dhurath/forest-3/20x5.c", "room");
    setCoordinate(20, 6,
        "/areas/tol-dhurath/forest-3/20x6.c", "path");
    setCoordinate(20, 7,
        "/areas/tol-dhurath/forest-3/20x7.c", "room");
    setCoordinate(20, 8,
        "/areas/tol-dhurath/forest-3/20x8.c", "room");
    setCoordinate(21, 2,
        "/areas/tol-dhurath/forest-3/21x2.c", "path");
    setCoordinate(21, 3,
        "/areas/tol-dhurath/forest-3/21x3.c", "path");
    setCoordinate(21, 4,
        "/areas/tol-dhurath/forest-3/21x4.c", "room");
    setCoordinate(21, 5,
        "/areas/tol-dhurath/forest-3/21x5.c", "room");
    setCoordinate(21, 6,
        "/areas/tol-dhurath/forest-3/21x6.c", "path");
    setCoordinate(22, 3,
        "/areas/tol-dhurath/forest-3/22x3.c", "path");
    setCoordinate(22, 4,
        "/areas/tol-dhurath/forest-3/22x4.c", "path");
    setCoordinate(22, 5,
        "/areas/tol-dhurath/forest-3/22x5.c", "path");
    setCoordinate(22, 6,
        "/areas/tol-dhurath/forest-3/22x6.c", "path");
    setCoordinate(22, 7,
        "/areas/tol-dhurath/forest-3/22x7.c", "room");
    setCoordinate(23, 3,
        "/areas/tol-dhurath/forest-3/23x3.c", "path");
    setCoordinate(23, 5,
        "/areas/tol-dhurath/forest-3/23x5.c", "path");
    setCoordinate(23, 6,
        "/areas/tol-dhurath/forest-3/23x6.c", "room");
    setCoordinate(23, 7,
        "/areas/tol-dhurath/forest-3/23x7.c", "path");
    setCoordinate(23, 8,
        "/areas/tol-dhurath/forest-3/23x8.c", "path");
    setCoordinate(23, 9,
        "/areas/tol-dhurath/forest-3/23x9.c", "path");
    setCoordinate(24, 3,
        "/areas/tol-dhurath/forest-3/24x3.c", "path");
    setCoordinate(24, 4,
        "/areas/tol-dhurath/forest-3/24x4.c", "entry");
    setCoordinate(24, 5,
        "/areas/tol-dhurath/forest-3/24x5.c", "path");
    setCoordinate(24, 6,
        "/areas/tol-dhurath/forest-3/24x6.c", "path");
    setCoordinate(24, 7,
        "/areas/tol-dhurath/forest-3/24x7.c", "path");
    setCoordinate(24, 8,
        "/areas/tol-dhurath/forest-3/24x8.c", "path");
    setCoordinate(24, 9,
        "/areas/tol-dhurath/forest-3/24x9.c", "path");
    setCoordinate(2, 0,
        "/areas/tol-dhurath/forest-3/2x0.c", "path");
    setCoordinate(2, 1,
        "/areas/tol-dhurath/forest-3/2x1.c", "room");
    setCoordinate(2, 7,
        "/areas/tol-dhurath/forest-3/2x7.c", "room");
    setCoordinate(2, 8,
        "/areas/tol-dhurath/forest-3/2x8.c", "room");
    setCoordinate(3, 0,
        "/areas/tol-dhurath/forest-3/3x0.c", "path");
    setCoordinate(3, 1,
        "/areas/tol-dhurath/forest-3/3x1.c", "room");
    setCoordinate(3, 6,
        "/areas/tol-dhurath/forest-3/3x6.c", "path");
    setCoordinate(3, 7,
        "/areas/tol-dhurath/forest-3/3x7.c", "path");
    setCoordinate(3, 8,
        "/areas/tol-dhurath/forest-3/3x8.c", "path");
    setCoordinate(4, 0,
        "/areas/tol-dhurath/forest-3/4x0.c", "path");
    setCoordinate(4, 1,
        "/areas/tol-dhurath/forest-3/4x1.c", "path");
    setCoordinate(4, 2,
        "/areas/tol-dhurath/forest-3/4x2.c", "path");
    setCoordinate(4, 3,
        "/areas/tol-dhurath/forest-3/4x3.c", "path");
    setCoordinate(4, 4,
        "/areas/tol-dhurath/forest-3/4x4.c", "room");
    setCoordinate(4, 5,
        "/areas/tol-dhurath/forest-3/4x5.c", "path");
    setCoordinate(4, 6,
        "/areas/tol-dhurath/forest-3/4x6.c", "room");
    setCoordinate(4, 8,
        "/areas/tol-dhurath/forest-3/4x8.c", "path");
    setCoordinate(5, 1,
        "/areas/tol-dhurath/forest-3/5x1.c", "path");
    setCoordinate(5, 2,
        "/areas/tol-dhurath/forest-3/5x2.c", "path");
    setCoordinate(5, 8,
        "/areas/tol-dhurath/forest-3/5x8.c", "path");
    setCoordinate(5, 9,
        "/areas/tol-dhurath/forest-3/5x9.c", "room");
    setCoordinate(6, 0,
        "/areas/tol-dhurath/forest-3/6x0.c", "path");
    setCoordinate(6, 1,
        "/areas/tol-dhurath/forest-3/6x1.c", "room");
    setCoordinate(6, 8,
        "/areas/tol-dhurath/forest-3/6x8.c", "path");
    setCoordinate(7, 0,
        "/areas/tol-dhurath/forest-3/7x0.c", "path");
    setCoordinate(7, 3,
        "/areas/tol-dhurath/forest-3/7x3.c", "path");
    setCoordinate(7, 4,
        "/areas/tol-dhurath/forest-3/7x4.c", "path");
    setCoordinate(7, 5,
        "/areas/tol-dhurath/forest-3/7x5.c", "room");
    setCoordinate(7, 8,
        "/areas/tol-dhurath/forest-3/7x8.c", "path");
    setCoordinate(8, 0,
        "/areas/tol-dhurath/forest-3/8x0.c", "path");
    setCoordinate(8, 1,
        "/areas/tol-dhurath/forest-3/8x1.c", "room");
    setCoordinate(8, 3,
        "/areas/tol-dhurath/forest-3/8x3.c", "path");
    setCoordinate(8, 8,
        "/areas/tol-dhurath/forest-3/8x8.c", "room");
    setCoordinate(8, 9,
        "/areas/tol-dhurath/forest-3/8x9.c", "path");
    setCoordinate(9, 0,
        "/areas/tol-dhurath/forest-3/9x0.c", "room");
    setCoordinate(9, 1,
        "/areas/tol-dhurath/forest-3/9x1.c", "path");
    setCoordinate(9, 2,
        "/areas/tol-dhurath/forest-3/9x2.c", "path");
    setCoordinate(9, 3,
        "/areas/tol-dhurath/forest-3/9x3.c", "room");
    setCoordinate(9, 4,
        "/areas/tol-dhurath/forest-3/9x4.c", "path");
    setCoordinate(9, 5,
        "/areas/tol-dhurath/forest-3/9x5.c", "path");
    setCoordinate(9, 8,
        "/areas/tol-dhurath/forest-3/9x8.c", "path");
    setCoordinate(9, 9,
        "/areas/tol-dhurath/forest-3/9x9.c", "path");

    // MapIcons
}

