//*****************************************************************************
// Copyright (c) 2017-2026 - Allen Cummings, RealmsMUD, All rights reserved. See
//                      the accompanying LICENSE file for details.
//*****************************************************************************
virtual inherit "/lib/items/book.c";

/////////////////////////////////////////////////////////////////////////////
protected void Setup()
{
    set("name", "A Chronicle of the Eastern Lands, Volume IV");
    set("short", "A worn leather-bound chronicle, Volume IV");
    set("title", "A Chronicle of the Eastern Lands, Volume IV: "
        "The Modern Age");
    set("aliases", ({ "chronicle", "volume iv", "volume 4", "book",
        "chronicle volume iv", "chronicle volume 4" }));
    set("long", "The newest of the chronicle volumes, bound in the "
        "same style as its predecessors but with less wear. The "
        "spine reads: 'A Chronicle of the Eastern Lands, Volume IV: "
        "The Modern Age.' The final entries are written in a "
        "noticeably different, more hurried hand.");

    addChapter("Shadows in the Mountains",
        "Year 2012: The orcs flee the Mirost region and descend "
        "upon Hillgarath. Rumors spread of hordes of the dead "
        "arising in the mountains.\n\n"
        "Year 2018: Hillgarath and Eledhel investigate Mirost. "
        "They are greeted with silence, though the way appears "
        "barred beyond the Halls of Kheleus.\n\n"
        "Year 2095: Zarnedh 'the Great' seizes the throne of "
        "Kharand.\n\n"
        "Year 2098: The kingdom of Kharand is united under "
        "Zarnedh's sway.\n\n"
        "Year 2104: Hillgarath and Eledhel attempt to re-establish "
        "the old alliance with the lands between Kharand and the "
        "Gap of Delerath. They meet with little success, only "
        "Linmir and Meledwath renewing the alliance.\n\n"
        "Year 2108: Kharand annexes Nernem and Zhendulach.\n\n"
        "Year 2112: Eslarach and Endurghul annexed by Kharand.\n\n"
        "Year 2113: Khendazach annexed by Kharand.\n\n"
        "Year 2183: Andurath annexed by Kharand. Now seriously "
        "alarmed, the remaining nations of the Lonis Vale join "
        "the alliance.\n\n"
        "Year 2194: Emendacil abdicates the throne of Hillgarath "
        "to his son Beren.\n\n"
        "Year 2213: Arvadan abdicates the throne of Eledhel to "
        "his son Areladur.");

    addChapter("The Rise and Fall of Zarnedh",
        "Year 2226: Celebgaer falls to Kharand.\n\n"
        "Year 2227: Areladur slain in battle with Kharand. The "
        "Drell conspiracy in Eledhel - civil war ensues as "
        "Artotis son of Areladur's claim is contested by Torma "
        "Drell on behalf of his son. In Eledhel's absence, "
        "Gildaer, Tirnost, and Dor-Edhel fall to Kharand.\n\n"
        "Year 2228: Drell marches on Eledhel and his army is "
        "annihilated by Artotis's forces. Torma and his son are "
        "slain in battle. Artotis grants clemency to the "
        "remaining Drell family. Lady Drell moves the family to "
        "newly-founded Ethyl Tirath and changes her surname to "
        "Belethon.\n\n"
        "Year 2231: Dyrinthia falls to Kharand.\n\n"
        "Year 2234: Caranost and Menadrost annexed by Kharand.\n\n"
        "Year 2235: Hirnost annexed by Kharand.\n\n"
        "Year 2237: Khazurath and Ost-yn-Thudyl declare war on "
        "Kharand.\n\n"
        "Year 2243: Kirnost annexed by Kharand, Meledwath invaded.\n\n"
        "Year 2244: Meledwath crumbles. Helcarion, Celebdur, and "
        "Meluin fall to Kharand. Celebduil besieged. The armies "
        "of Eledhel mass around Celebduil in an attempt to break "
        "the siege. Hillgarath is put to trial around Dor-Lonis.\n\n"
        "Year 2245: Zarnedh 'the Great' passes. The throne goes to "
        "his son Zarnedh II.\n\n"
        "Year 2247: Dor-Lonis falls. The armies of Hillgarath "
        "retreat to Delerath Keep and Linmir.\n\n"
        "Year 2249: The armies of Eledhel gain great respect having "
        "broken the siege of Celebduil and routed the southern "
        "enemy armies. They split: some march south to liberate "
        "Helcarion while the others go to the succor of Linmir.\n\n"
        "Year 2261: Kharand collapses under the pressure of Eledhel "
        "and Hillgarath. Zarnedh slain in bloody coup. Andurath "
        "re-established.");

    addChapter("The Birth of Tirnost and the League",
        "Year 2264: The Kingdom of Tirnost is born, encompassing "
        "the cities of Tirnost, Gildaer, Celebgaer, Dor-Edhel, "
        "Dyrinthia, Enelmir, Zhendulan, Ulmar, Findulien, and "
        "Ciryanost. Hrongdil becomes its first king.\n\n"
        "Year 2281: Ermondar of Kirnost now aged and childless "
        "due to the wars, wills his kingdom to Hrongdil.\n\n"
        "Year 2290: Kirnost merges with Tirnost.\n\n"
        "Year 2316: Tirnost, Lonis, Linmir, and Meledwath form the "
        "League of the Lonis Vale, a tight alliance designed to "
        "protect the kingdoms from aggression by Kharand and "
        "Andurath.\n\n"
        "Year 2317: Menadrost joins the League.\n\n"
        "Year 2351: Romenadur assumes the throne of Hillgarath.\n\n"
        "Year 2354: Romenadur II, eldest son of the king, falls "
        "in battle with orcs.\n\n"
        "Year 2358: Hillgarath pledges two divisions of its army "
        "and a brigade of Werric Knights to the League.\n\n"
        "Year 2359: Eledhel matches Hillgarath's contributions. "
        "Eledhel and Hillgarath sign the Pact of Serach. Each "
        "nation will send an army division to the other for "
        "mutual protection.\n\n"
        "Year 2366: Alendur, second son of King Romenadur, slain "
        "in battle near Helcarion.\n\n"
        "Year 2368: Aradan assumes the throne of Eledhel.");

    addChapter("Plague, War, and the Kellgaard Dynasty",
        "Year 2379: Romenadur slain in battle with Kharand. "
        "Telmedil assumes the throne and is slain in the same "
        "battle. Romenadur's nephew Calemacil assumes the "
        "throne of Hillgarath.\n\n"
        "Year 2384: Plague ravages Eledhel, Hillgarath, and the "
        "lands of the League. Meledwath has no heir and the "
        "League takes on leadership. Calemacil survives but "
        "loses his wife and two children.\n\n"
        "Year 2385: Orcs attack and lay siege to Arnost. Calemacil "
        "is slain in battle. Given the lack of heir and fearing "
        "instability, Daedrun assumes the throne of Hillgarath "
        "as Daedrun Kellgaard I.\n\n"
        "Year 2416: Aradan slain in battle by Hirnost. Ardenel "
        "assumes the throne of Eledhel.");

    addChapter("The Orcish Campaigns",
        "Year 2484: The orcs in the mountains in northern Eledhel "
        "increase in number. Ardenel musters an army to deal "
        "with them.\n\n"
        "Year 2496: Ardenel slain in battle with the orcs. "
        "Arendil assumes the throne of Eledhel.\n\n"
        "Year 2503: Arendil sacks the orcish stronghold of "
        "Eznairun.\n\n"
        "Year 2504: Arendil razes Eralkidh and holes the orcs "
        "up in their fortress at Gharndar.\n\n"
        "Year 2511: Gharndar captured and put to fire by "
        "Arendil.\n\n"
        "Year 2518: Andurath besieges Helcarion. Arendil brings "
        "the fleet to Helcarion's aid.\n\n"
        "Year 2522: King Beltar of Linmir weds Queen Ellen of "
        "Tirnost. As the two nations merge, the League ends, "
        "replaced by the Empire of Tirnost. They form an alliance "
        "of mutual protection with Hillgarath and Eledhel.\n\n"
        "Year 2523: Menadrost formally joins the alliance.\n\n"
        "Year 2586: Kharand invades western Tirnost. Arendil of "
        "Eledhel and Lord Kellgaard of Hillgarath march to "
        "Tirnost's aid. Menadrost remains silent and is expelled "
        "from the alliance.\n\n"
        "Year 2625: Arelendur assumes the throne of Eledhel.\n\n"
        "Year 2671: The orcs in northern Eledhel and Hillgarath "
        "again become a problem. Tirnost, Eledhel, and Hillgarath "
        "muster armies. The Battle of Zhaghadel begins.\n\n"
        "Year 2674: The orcs are routed and are not heard from for "
        "the next two hundred fifty years. With the orcs in hiding "
        "and Andurath and Kharand quiet, a long period of peace "
        "begins.");

    addChapter("The Gathering Storm",
        "Year 2833: Ardenel II assumes the throne of Eledhel.\n\n"
        "Year 2870: The orcs again harry the lands in the north. "
        "Kharand and Andurath begin skirmishing on the borders of "
        "Tirnost. From this year forward, war never ceases during "
        "Ardenel's reign.\n\n"
        "Year 2916: Ardenel of Eledhel, King Uldor III of Tirnost, "
        "and Lord Kellgaard of Hillgarath hold council amid fears "
        "of growing darkness. Uldor notes activity in Kharand and "
        "Andurath and rumors of darkness from Utumnadh. Lord "
        "Kellgaard discusses the re-emergence of the Keepers of "
        "the Night.\n\n"
        "Year 2926: Aradin, son of Ardenel, takes charge of the "
        "armies of Eledhel around Helcarion.\n\n"
        "Year 2940: Orcs lay siege to Ethyl Tirath.\n\n"
        "Year 2941: The orcs are utterly destroyed, their "
        "strongholds of Eznairun, Eralkidh, and Gharndar utterly "
        "wiped from the surface of the world. The king's sons "
        "Aredec and Arador, as well as the king's nephew Aramed, "
        "performed with great distinction.\n\n"
        "[The chronicle ends here. The final entry is written in "
        "a rushed hand, as though the scribe was interrupted "
        "mid-thought. Spatters of what might be ink - or might "
        "be blood - mark the last page.]");
}
